import { beforeEach, afterEach, it, expect, vi } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, appendFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { createRequire } from 'node:module';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { Server } from 'node:http';
import { Readable } from 'node:stream';
import { HumanGoalService } from '../../src/core/human-goal-workflow/service.js';
import { startServer } from '../../src/human-goal-workbench/server.js';
import { digest } from '../../src/core/human-goal-workflow/types.js';
import { projectRounds } from '../../src/core/human-goal-workflow/rounds.js';
const {JSDOM}=createRequire(import.meta.url)('jsdom');
let root:string,source:string,evidence:string,service:HumanGoalService,config:any;
beforeEach(()=>{root=mkdtempSync(join(tmpdir(),'round-ui-SYNTHETIC-'));source=join(root,'source');evidence=join(root,'evidence');mkdirSync(source);mkdirSync(evidence);writeFileSync(join(source,'main.ts'),'export const original = true;\n');config={projects:[{id:'self',label:'synthetic self',sourceRoot:source,scope:['.'],revision:'test',sourceKind:'working-tree',subjectId:'self',caseRole:'self-case',evidenceRoots:[evidence]}],dataDir:join(root,'data'),port:0,analyzer:{timeoutMs:null}};service=new HumanGoalService(config,{revision:'unused',async analyze(){throw new Error('no model should run');}});service.feedback('self',{expectedGeneration:0,idempotencyKey:'goal',kind:'desired-change',originalText:'See real changes <img src=x>',author:'test',provenance:'synthetic test',analyze:false});});
afterEach(async()=>{vi.restoreAllMocks();await service.close();rmSync(root,{recursive:true,force:true});});
function enrollment(){const s=service.read('self');return {id:'run',projectId:'self',repoRoot:source,worktreeRoot:source,branch:'test',tool:'codex-exec',toolVersion:'0.155.0-alpha.2.6',taskId:'task',roundId:'round',attemptId:'attempt',producerId:'producer',mode:'live',goalHash:s.goals[0].hash,feedbackIds:[s.feedback[0].id],purpose:'Observe real source changes',clauseIds:s.goals[0].clauses.map(c=>c.id),journeyIds:[],selectedActionIds:[],acceptedPlan:null,beforeSnapshotId:service.rounds.capture('self').id,stream:{rootIndex:0,path:'raw.jsonl'},deferredBenefit:null};}
it('real HTTP enrollment, CLI routing to server lease, source deltas, strict roots and restart follower',async()=>{
 let app=await startServer(service);try{const request=async(op:string,body?:unknown)=>fetch(`${app.url}/api/projects/self/${op}`,{method:body?'POST':'GET',headers:body?{Origin:app.url,'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined});
 const r=enrollment();expect((await request('round-enroll',r)).status).toBe(200);writeFileSync(join(evidence,'raw.jsonl'),'{"type":"turn.started"}\n');service.follower.poll();writeFileSync(join(source,'main.ts'),'export const modified = true;\n');appendFileSync(join(evidence,'raw.jsonl'),'{"type":"item.completed","item":{"id":"x","type":"agent_message","text":"SECRET fixed"}}\n{"type":"turn.completed"}\n');expect((await request('round-replay',{registrationId:'run'})).status).toBe(200);
 const projected:any=await(await request('state')).json();expect(projected.rounds.rounds[0].deltas).toHaveLength(1);expect(projected.rounds.rounds[0].verified).toHaveLength(0);expect(JSON.stringify(projected)).not.toContain('SECRET');expect((await request('round-enroll',{...r,id:'bad',stream:{rootIndex:7,path:'raw.jsonl'}})).status).toBe(400);expect((await request('round-snapshot',{import:{rootIndex:0,path:'../source/main.ts',sha256:'a'.repeat(64)}})).status).toBe(400);
 const configPath=join(root,'config.json');writeFileSync(configPath,JSON.stringify(config));const result=await promisify(execFile)(process.execPath,['--import','tsx','scripts/project-os-rounds.ts','status','--config',configPath,'--project','self']);expect(JSON.parse(result.stdout).rounds[0].id).toBe('round');
 await app.close();service=new HumanGoalService(config);app=await startServer(service);const reopened:any=await(await fetch(`${app.url}/api/projects/self/rounds`)).json();expect(reopened.rounds[0].eventCount).toBe(3);expect(reopened.rounds[0].deltas).toEqual(projected.rounds.rounds[0].deltas);
 }finally{await app.close();}
});
it('DOM shows real rounds before any analysis, preserves literal user text, selection and source navigation',async()=>{
 const r=enrollment();service.rounds.enroll('self',r);writeFileSync(join(evidence,'raw.jsonl'),'{"type":"turn.started"}\n');service.follower.poll();writeFileSync(join(source,'main.ts'),'export const modified = true;\n');appendFileSync(join(evidence,'raw.jsonl'),'{"type":"turn.completed"}\n');service.follower.poll();const state=service.read('self'),projection=projectRounds(state);
 const dom=new JSDOM(readFileSync('src/human-goal-workbench/index.html','utf8'),{url:'http://127.0.0.1:9999',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;let selectedPath='';w.matchMedia=()=>({matches:false});w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.fetch=async(url:string)=>({ok:true,json:async()=>{if(url==='/api/projects')return {projects:config.projects};if(url.includes('/source?')){selectedPath=url;return {text:'1: export const modified = true;',sha256:'a'.repeat(64)};}return {...state,rounds:projection,diagnosisStatus:'not-analyzed'};}});
 w.eval(readFileSync('src/human-goal-workbench/client.js','utf8'));await new Promise(r=>setTimeout(r,40));try{const d=w.document;expect(d.getElementById('overall-diagnosis').textContent).toContain('尚无整体诊断');expect(d.getElementById('round-detail').textContent).toContain('Observe real source changes');expect(d.getElementById('round-detail').textContent).toContain('main.ts');expect(d.querySelectorAll('.node')).toHaveLength(0);expect(d.querySelector('img')).toBeNull();expect(d.querySelector('.round-link').getAttribute('aria-pressed')).toBe('true');d.querySelector('#round-detail .source-ref').click();await new Promise(r=>setTimeout(r,10));expect(selectedPath).toContain('sha256=');expect(d.getElementById('dialog-body').textContent).toContain('modified');expect(readFileSync('src/human-goal-workbench/client.js','utf8')).not.toMatch(/\.innerHTML\s*=/);}finally{dom.window.close();}
});

it('deterministic API handler projection validates enrollment and public privacy without a socket',async()=>{
 // This separate unit check does not replace the real HTTP test above, which remains mandatory.
 vi.spyOn(Server.prototype,'listen').mockImplementation(function(this:Server,...args:any[]){queueMicrotask(()=>args.at(-1)());return this;});
 vi.spyOn(Server.prototype,'close').mockImplementation(function(this:Server,callback?:any){callback?.();return this;});
 const app=await startServer(service,9999);
 const request=(op:string,body?:unknown)=>new Promise<{status:number;data:any}>(resolve=>{const req=Readable.from(body?[Buffer.from(JSON.stringify(body))]:[]) as any;req.url=`/api/projects/self/${op}`;req.method=body?'POST':'GET';req.headers={host:'127.0.0.1:9999',origin:'http://127.0.0.1:9999','content-type':'application/json'};const res={statusCode:200,setHeader(){},end(value:string){resolve({status:this.statusCode,data:JSON.parse(value)});}};app.server.emit('request',req,res);});
 try{const r=enrollment();expect((await request('round-enroll',r)).status).toBe(200);writeFileSync(join(evidence,'raw.jsonl'),'{"type":"turn.started"}\n{"type":"turn.completed"}\n');expect((await request('round-replay',{registrationId:'run'})).data.status).toBe('terminal');const state=await request('state');expect(state.data.rounds.rounds).toHaveLength(1);expect(state.data.roundAnalysisPolicy).toEqual({enabled:false,historical:false});expect((await request('rounds')).data.analysisJobs).toEqual([]);expect(state.data.rounds.rounds[0].mode).toBe('live');expect((await request('round-snapshot',{unrecognized:true})).status).toBe(400);expect((await request('round-replay',{registrationId:'run',root:'/arbitrary'})).status).toBe(400);expect((await request('round-evidence',{rootIndex:99,path:'outside',sha256:'a'.repeat(64)})).status).toBe(400);}finally{await app.close();}
});

it('compact round purpose, collapsed evidence, affected nodes and edges, and stale mapping share the selected round',async()=>{
 await service.close();service=new HumanGoalService(config,{revision:'SYNTHETIC-map',async analyze(input){const f=input.source.files[0],ref={path:f.path,sha256:f.sha256,start:1,end:1};return {purpose:'Read actual source',purposeRefs:[ref],limitations:[],modules:['a','b'].map(id=>({id,title:`Module ${id}`,kind:'discovered',responsibility:'test',inputs:[],outputs:[],refs:[ref],supersedes:[]})),edges:[{id:'edge',from:'a',to:'b',label:'Source flow',expected:'deliver',actual:'static only',refs:[ref]}],alignments:input.goal!.clauses.map((c:any)=>({id:`align-${c.id}`,clauseIds:[c.id],targetIds:['a','b','edge'],status:'implemented-unverified',rationale:'test',refs:[ref]})),gaps:[],conflicts:[],changes:[],coverageNotes:'synthetic',feedbackResponse:'synthetic'};}});
 const r=enrollment();service.rounds.enroll('self',r);writeFileSync(join(source,'main.ts'),'export const changed=true;\n');writeFileSync(join(evidence,'raw.jsonl'),'{"type":"turn.started"}\n{"type":"turn.completed"}\n');service.follower.poll();service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'map'});await service.idle();
 const next={...r,id:'later',roundId:'later-round',attemptId:'later-attempt',producerId:'later-producer',taskId:'later-task',purpose:'Later purpose',beforeSnapshotId:service.rounds.capture('self').id,stream:{rootIndex:0,path:'later.jsonl'}};service.rounds.enroll('self',next);writeFileSync(join(source,'main.ts'),'export const later=true;\n');writeFileSync(join(evidence,'later.jsonl'),'{"type":"turn.started"}\n{"type":"turn.completed"}\n');service.follower.poll();const s=service.read('self'),rounds=projectRounds(s),v={...s.views[0],statuses:{a:'implemented-unverified',b:'implemented-unverified',edge:'implemented-unverified'}};
 const dom=new JSDOM(readFileSync('src/human-goal-workbench/index.html','utf8'),{url:'http://127.0.0.1:9999',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;w.matchMedia=()=>({matches:false});w.fetch=async(url:string)=>({ok:true,json:async()=>url==='/api/projects'?{projects:config.projects}:{...s,views:[v],currentView:0,roundViews:[v],rounds,diagnosisStatus:'stale'}});w.eval(readFileSync('src/human-goal-workbench/client.js','utf8'));await new Promise(r=>setTimeout(r,40));
 try{const d=w.document;expect(d.querySelector('.round-link strong').textContent).toBe('Later purpose');expect(d.querySelector('.round-evidence').open).toBe(false);expect(d.querySelector('.goal-evidence').open).toBe(false);expect(d.querySelector('.round-mapping').textContent).toContain('映射待更新');expect(d.querySelectorAll('.round-affected')).toHaveLength(0);
 d.querySelectorAll('.round-link')[1].click();expect(d.querySelector('.round-mapping').textContent).toContain('同源');expect(d.querySelectorAll('.node.round-affected')).toHaveLength(2);expect(d.querySelectorAll('.edge.round-affected')).toHaveLength(1);expect(d.querySelector('.round-evidence').textContent).toContain(r.goalHash);expect(d.querySelector('.round-evidence').textContent).toContain('See real changes <img src=x>');expect(d.querySelector('img')).toBeNull();
 const edge=d.querySelector('.edge');edge.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));expect(d.querySelector('#detail-title').textContent).toContain('Source flow');expect(d.querySelector('#detail').textContent).toContain('static only');expect(d.querySelector('.round-evidence summary')).not.toBeNull();
 }finally{w.close();}
});

it('goal navigation uses G2 independently of revision 213 and a pending older G1 model',async()=>{
 service.feedback('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'goal2',kind:'desired-change',originalText:'Second human goal',author:'human',provenance:'test',analyze:false});const s=service.read('self');s.generation=213;
 const dom=new JSDOM(readFileSync('src/human-goal-workbench/index.html','utf8'),{url:'http://127.0.0.1:9999',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;w.matchMedia=()=>({matches:false});w.fetch=async(url:string)=>({ok:true,json:async()=>url==='/api/projects'?{projects:config.projects}:{...s,rounds:projectRounds(s),attempts:[{id:'old-analysis',state:'running',goalVersion:1,totalBudgetMs:null,createdAt:new Date().toISOString(),usedMs:0}]}});
 w.eval(readFileSync('src/human-goal-workbench/client.js','utf8'));await new Promise(r=>setTimeout(r,40));try{const d=w.document;expect(d.getElementById('generation').textContent).toBe('G2');expect(d.getElementById('save-state').textContent).toContain('revision 213');expect(d.getElementById('job').textContent).toContain('目标 G1');expect(d.getElementById('goal-summary').textContent).toBe('Second human goal');}finally{w.close();}
});
it('round UI separates unobserved from observed zero and shows literal evidence scope with legacy unknowns',async()=>{
 const r={...enrollment(),mode:'historical-replay'};service.rounds.enroll('self',r);writeFileSync(join(evidence,'raw.jsonl'),'\x7b"type":"turn.started"}\n');service.follower.follow('self','run');let s=service.read('self'),projection:any=projectRounds(s);
 const dom=new JSDOM(readFileSync('src/human-goal-workbench/index.html','utf8'),{url:'http://127.0.0.1:9999',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;w.matchMedia=()=>({matches:false});w.fetch=async(url:string)=>({ok:true,json:async()=>url==='/api/projects'?{projects:config.projects}:{...s,rounds:projection}});w.eval(readFileSync('src/human-goal-workbench/client.js','utf8'));await new Promise(r=>setTimeout(r,40));try{
 const d=w.document;expect(d.querySelector('.round-summary').textContent).toContain('尚无本轮源码观察，变化未知');expect(d.querySelector('.round-summary').textContent).not.toContain('0 项');
 service.rounds.checkpoint('self','run');s=service.read('self');projection=projectRounds(s);projection.rounds[0].verified=[{result:'passed',targetIds:['target'],clauseIds:['clause'],rawHash:'a'.repeat(64),scopeSummary:'Checks <img src=x> shell changes',limitations:['No real provider']},{result:'passed',targetIds:['legacy'],clauseIds:['clause'],rawHash:'b'.repeat(64)}];await w.eval('refresh(true)');expect(d.querySelector('.round-summary').textContent).toContain('0 项文件变化（截至最近观察）');expect(d.querySelector('#round-detail').textContent).toContain(projection.rounds[0].lastSourceObservedAt);expect(d.querySelector('.round-evidence').textContent).toContain('Checks <img src=x> shell changes');expect(d.querySelector('.round-evidence').textContent).toContain('No real provider');expect(d.querySelector('.round-evidence').textContent).toContain('验证范围说明未提供');expect(d.querySelector('img')).toBeNull();
 }finally{w.close();}
});

// Synthetic DOM fixtures exercise presentation only; they are never imported as live case evidence.
async function graphFixture(){
 await service.close();service=new HumanGoalService(config,{revision:'SYNTHETIC-camera',async analyze(input){const f=input.source.files[0],ref={path:f.path,sha256:f.sha256,start:1,end:1};return {purpose:'Synthetic multi-column graph',purposeRefs:[ref],limitations:[],modules:['a','b','c','d'].map(id=>({id,title:`Readable module ${id}`,kind:'discovered',responsibility:'test',inputs:[],outputs:[],refs:[ref],supersedes:[]})),edges:['b','c','d'].map((id,i)=>({id:`edge-${id}`,from:['a','b','c'][i],to:id,label:`Flow to ${id}`,expected:'deliver',actual:'static only',refs:[ref]})),alignments:input.goal!.clauses.map((c:any)=>({id:`align-${c.id}`,clauseIds:[c.id],targetIds:['a'],status:'implemented-unverified',rationale:'synthetic',refs:[ref]})),gaps:[],conflicts:[],changes:[],coverageNotes:'synthetic',feedbackResponse:'synthetic'};}});
 const r=enrollment();service.rounds.enroll('self',r);writeFileSync(join(evidence,'raw.jsonl'),'{"type":"turn.started"}\n{"type":"turn.completed"}\n');service.follower.poll();service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'graph'});await service.idle();return service.read('self');
}
async function graphDOM(payload:any,options:{width?:number;height?:number;pref?:any}={}){
 const dom=new JSDOM(readFileSync('src/human-goal-workbench/index.html','utf8'),{url:'http://127.0.0.1:9999',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
 let size={width:options.width??800,height:options.height??400};let resize:()=>void=()=>{};
 w.matchMedia=()=>({matches:false});w.ResizeObserver=class {constructor(callback:()=>void){resize=callback;}observe(){}};
 w.document.getElementById('graph-wrap').getBoundingClientRect=()=>({...size,x:0,y:0,top:0,left:0,right:size.width,bottom:size.height});
 w.document.getElementById('graph').setPointerCapture=()=>{};
 if(options.pref)w.localStorage.setItem('hg-reading',JSON.stringify(options.pref));
 w.fetch=async(url:string)=>({ok:true,json:async()=>url==='/api/projects'?{projects:config.projects}:payload});
 w.eval(readFileSync('src/human-goal-workbench/client.js','utf8'));await new Promise(r=>setTimeout(r,40));
 return {w,d:w.document,resize:(width:number,height:number)=>{size={width,height};resize();},camera:()=>w.document.querySelector('#scene')?.getAttribute('transform')};
}
function graphPayload(s:any){const views=s.views.map((v:any)=>({...v,statuses:Object.fromEntries([...v.analysis.modules,...v.analysis.edges].map((t:any)=>[t.id,'implemented-unverified']))}));return {...s,views,rounds:projectRounds(s),roundViews:views,diagnosisStatus:'current'};}

it('inline scoped verification uses qualified current round proof, readable targets, failures first and explicit uncertainty',async()=>{
 const s=await graphFixture(),round=projectRounds(s).rounds[0],goal=s.goals.at(-1)!;
 const proof={sourceHash:round.after!.sourceHash,goalHash:goal.hash,producer:'SYNTHETIC-test',targetIds:['a','edge-b'],clauseIds:goal.clauses.map(c=>c.id),rawRecord:'fixture',rawHash:'a'.repeat(64),qualified:true,qualificationReason:'synthetic projection fixture',invocation:null,result:'passed',createdAt:new Date(Date.now()+1000).toISOString()};
 s.observations=[{...proof,id:'pass',scopeSummary:'Passing <img src=x> scoped behavior',limitations:['No human acceptance']},{...proof,id:'failure',targetIds:['edge-b'],result:'failed',scopeSummary:'Actual scoped failure',limitations:['HTTP path only']},{...proof,id:'legacy'},{...proof,id:'unqualified',qualified:false,scopeSummary:'UNQUALIFIED MUST STAY OUT'},{...proof,id:'wrong-source',sourceHash:'b'.repeat(64),scopeSummary:'WRONG SOURCE MUST STAY OUT'},{...proof,id:'old-goal',goalHash:'c'.repeat(64),scopeSummary:'WRONG GOAL MUST STAY OUT'},{...proof,id:'old-time',createdAt:'2020-01-01T00:00:00Z',scopeSummary:'STALE MUST STAY OUT'}] as any;
 const payload=graphPayload(s),ui=await graphDOM(payload);try{
 const inline=ui.d.querySelector('.round-verification');expect(inline.closest('details')).toBeNull();expect(ui.d.querySelector('.round-evidence').open).toBe(false);expect(inline.querySelector('.scoped-check strong').textContent).toBe('失败 · Flow to b');expect(inline.textContent).toContain('Readable module a');expect(inline.textContent).toContain('Passing <img src=x> scoped behavior');expect(inline.textContent).toContain('No human acceptance');expect(inline.textContent).toContain('验证范围说明未提供');expect(inline.textContent).toContain('仍待确认');expect(inline.textContent).not.toContain('MUST STAY OUT');expect(ui.d.querySelector('img')).toBeNull();expect(ui.d.querySelector('.round-evidence').textContent).toContain(proof.rawHash);
 payload.goals=[...s.goals,{...goal,version:2,hash:'d'.repeat(64)}];payload.rounds=projectRounds({...s,goals:payload.goals});await ui.w.eval('refresh(true)');expect(ui.d.querySelectorAll('.round-verification .scoped-check')).toHaveLength(0);expect(ui.d.querySelector('.round-verification').textContent).toContain('旧目标');expect(ui.d.querySelector('.round-summary').textContent).not.toContain('已有限定验证');
 }finally{ui.w.close();}
});
it('new graph fits full positive viewport, normal polling and selection renders preserve manual camera, full-map remains usable',async()=>{
 const s=await graphFixture(),payload=graphPayload(s),ui=await graphDOM(payload);try{
 const initial=ui.camera(),match=initial.match(/translate\(([-.\d]+) ([-.\d]+)\) scale\(([-.\d]+)\)/),[x,y,zoom]=match.slice(1).map(Number),bounds=ui.d.getElementById('graph-wrap').getBoundingClientRect();
 expect(zoom).toBeGreaterThanOrEqual(.85);expect(zoom).toBeLessThanOrEqual(1);expect(ui.d.querySelectorAll('.node')).toHaveLength(4);
 for(const node of ui.d.querySelectorAll('.node')){const [nx,ny]=node.getAttribute('transform').match(/translate\(([-.\d]+) ([-.\d]+)\)/).slice(1).map(Number),rect=node.querySelector('rect');expect(x+nx*zoom).toBeGreaterThanOrEqual(0);expect(y+ny*zoom).toBeGreaterThanOrEqual(0);expect(x+(nx+Number(rect.getAttribute('width')))*zoom).toBeLessThanOrEqual(bounds.width);expect(y+(ny+Number(rect.getAttribute('height')))*zoom).toBeLessThanOrEqual(bounds.height);}
 expect(ui.d.querySelectorAll('.edge')).toHaveLength(payload.views[0].analysis.edges.length);
 const svg=ui.d.getElementById('graph');svg.dispatchEvent(new ui.w.MouseEvent('pointerdown',{clientX:10,clientY:10,bubbles:true}));svg.dispatchEvent(new ui.w.MouseEvent('pointermove',{clientX:110,clientY:90,bubbles:true}));svg.dispatchEvent(new ui.w.MouseEvent('pointerup',{bubbles:true}));svg.dispatchEvent(new ui.w.WheelEvent('wheel',{deltaY:-10,bubbles:true}));const manual=ui.camera();expect(manual).not.toBe(initial);payload.generation++;await ui.w.eval('refresh()');expect(ui.camera()).toBe(manual);ui.d.getElementById('search').value='Readable';ui.d.getElementById('search').dispatchEvent(new ui.w.Event('input'));expect(ui.camera()).toBe(manual);ui.resize(900,420);expect(ui.camera()).toBe(manual);
 ui.d.querySelector('.node').dispatchEvent(new ui.w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));expect(ui.d.getElementById('detail-title').textContent).toBe('Readable module a');const selected=ui.camera();await ui.w.eval('refresh(true)');expect(ui.camera()).toBe(selected);expect(ui.d.querySelectorAll('#graph-list button')).toHaveLength(7);ui.d.getElementById('fit').click();expect(ui.camera()).not.toBe(selected);expect(ui.camera()).not.toContain('NaN');
 }finally{ui.w.close();}
});
it('hidden and zero-size graphs defer fitting until visible and never consume the pending camera binding',async()=>{
 const payload=graphPayload(await graphFixture()),ui=await graphDOM(payload,{width:0,height:0});try{
 expect(ui.camera()).toBe('translate(0 0) scale(1)');ui.d.getElementById('fit').click();expect(ui.camera()).toBe('translate(0 0) scale(1)');ui.d.getElementById('graph-wrap').style.visibility='hidden';ui.resize(800,400);expect(ui.camera()).toBe('translate(0 0) scale(1)');ui.d.getElementById('graph-wrap').style.visibility='visible';ui.resize(800,400);expect(ui.camera()).not.toBe('translate(0 0) scale(1)');const fit=ui.camera();ui.resize(0,0);ui.d.getElementById('fit').click();expect(ui.camera()).toBe(fit);
 }finally{ui.w.close();}
});
it('new current analysis fits once; explicit historical navigation restores each camera and affected disclosure',async()=>{
 const s=await graphFixture(),payload=graphPayload(s),ui=await graphDOM(payload);try{
 ui.d.getElementById('zoom-in').click();const manual=ui.camera(),first=payload.views[0];
 const next=JSON.parse(JSON.stringify(first));next.attemptId='SYNTHETIC-second-analysis';next.analysis.purpose='Latest current source analysis';next.analysis.modules.push({...next.analysis.modules[0],id:'extra',title:'Extra node'});next.analysis.edges.push({...next.analysis.edges[0],id:'extra-edge',from:'d',to:'extra'});
 payload.views=[first,next];payload.roundViews=[first,next];payload.currentView=1;payload.rounds.rounds.push({...payload.rounds.rounds[0],id:'second-round',purpose:'Second round',viewAttemptId:next.attemptId,touchedTargets:['extra','extra-edge'],next:'SECOND NEXT'});payload.rounds.rounds[0].next='FIRST NEXT';payload.rounds.revision++;await ui.w.eval('refresh(true)');
 expect(ui.camera()).not.toBe(manual);expect(ui.d.getElementById('purpose').textContent).toBe(next.analysis.purpose);expect(ui.d.querySelectorAll('.node')).toHaveLength(5);expect(ui.d.getElementById('map-context').hidden).toBe(true);expect(ui.d.getElementById('rounds-panel').hidden).toBe(true);
 expect(ui.d.getElementById('overall-diagnosis').textContent).not.toContain('FIRST NEXT');expect(ui.d.getElementById('overall-diagnosis').textContent).not.toContain('SECOND NEXT');
 const currentCamera=ui.camera();await ui.w.eval('refresh(true)');expect(ui.camera()).toBe(currentCamera);
 ui.d.getElementById('tab-rounds').click();expect(ui.d.getElementById('rounds-panel').hidden).toBe(false);ui.d.querySelectorAll('.round-link')[0].click();expect(ui.d.getElementById('purpose').textContent).toBe(next.analysis.purpose);expect(ui.camera()).toBe(currentCamera);
 expect(ui.d.querySelector('.round-targets').open).toBe(false);expect(ui.d.querySelector('.round-targets summary').textContent).toContain('2 个');expect(ui.d.querySelectorAll('.round-targets button')).toHaveLength(2);expect(ui.d.querySelectorAll('.round-affected')).toHaveLength(2);ui.d.querySelector('.round-targets').open=true;await ui.w.eval('refresh(true)');expect(ui.d.querySelector('.round-targets').open).toBe(true);
 ui.d.querySelector('.round-targets button').click();expect(ui.d.getElementById('detail-title').textContent).toBe('Extra node');expect(ui.d.getElementById('map-context').hidden).toBe(false);expect(ui.d.getElementById('overall-diagnosis').textContent).toContain('SECOND NEXT');expect(ui.d.getElementById('overall-diagnosis').textContent).not.toContain('FIRST NEXT');const selectedCurrentCamera=ui.camera();
 ui.d.getElementById('tab-rounds').click();ui.d.querySelectorAll('.round-link')[1].click();expect(ui.d.getElementById('purpose').textContent).toBe(next.analysis.purpose);expect(ui.d.querySelectorAll('.node')).toHaveLength(5);expect(ui.d.getElementById('map-context').hidden).toBe(true);
 ui.d.getElementById('round-map').click();expect(ui.camera()).toBe(manual);expect(ui.d.getElementById('purpose').textContent).toBe(first.analysis.purpose);expect(ui.d.querySelectorAll('.node')).toHaveLength(4);expect(ui.d.getElementById('map-context').hidden).toBe(false);expect(ui.d.getElementById('overall-diagnosis').textContent).toContain('FIRST NEXT');expect(ui.d.getElementById('overall-diagnosis').textContent).not.toContain('SECOND NEXT');
 await ui.w.eval('refresh(true)');expect(ui.camera()).toBe(manual);expect(ui.d.querySelectorAll('.node')).toHaveLength(4);
 ui.d.querySelector('#map-context button').click();expect(ui.camera()).toBe(selectedCurrentCamera);expect(ui.d.getElementById('purpose').textContent).toBe(next.analysis.purpose);expect(ui.d.getElementById('map-context').hidden).toBe(true);
 ui.d.getElementById('tab-rounds').click();ui.d.getElementById('round-map').click();expect(ui.camera()).toBe(manual);
 // Rebinding the explicitly opened round must display its newly bound graph.
 payload.rounds.rounds[0].viewAttemptId=next.attemptId;await ui.w.eval('refresh(true)');expect(ui.camera()).not.toBe(manual);expect(ui.d.getElementById('purpose').textContent).toBe(next.analysis.purpose);expect(ui.d.querySelectorAll('.node')).toHaveLength(5);
 }finally{ui.w.close();}
});
it('persisted camera is restored only for its exact project and graph binding, while a new analysis fits',async()=>{
 const payload=graphPayload(await graphFixture()),ui=await graphDOM(payload);let pref:any,manual:string;try{ui.d.getElementById('zoom-in').click();manual=ui.camera();pref=JSON.parse(ui.w.localStorage.getItem('hg-reading'));expect(pref.cameraBinding).toContain(payload.views[0].attemptId);}finally{ui.w.close();}
 const reopened=await graphDOM(payload,{pref});try{expect(reopened.camera()).toBe(manual!);}finally{reopened.w.close();}
 const changed=await graphDOM(payload,{pref:{...pref,cameraBinding:'old graph'}});try{expect(changed.camera()).not.toBe(manual!);}finally{changed.w.close();}
});

it('recovery UI distinguishes restored reception from historical source coverage and retains error and policy evidence',async()=>{
 const r=enrollment();service.rounds.enroll('self',r);writeFileSync(join(evidence,'raw.jsonl'),'{"type":"turn.started"}\n'+JSON.stringify({type:'item.completed',item:{id:'large',type:'command_execution',command:'PRIVATE',aggregated_output:'x'.repeat(545232)}})+'\n{"type":"turn.completed"}\n');service.follower.follow('self','run');await service.close();config.eventReadPolicy={maxRecordBytes:1048576};service=new HumanGoalService(config);service.follower.follow('self','run');const s=service.read('self'),rounds={...projectRounds(s),eventReadPolicy:service.config.eventReadPolicy};
 const dom=new JSDOM(readFileSync('src/human-goal-workbench/index.html','utf8'),{url:'http://127.0.0.1:9999',runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;w.matchMedia=()=>({matches:false});w.fetch=async(url:string)=>({ok:true,json:async()=>url==='/api/projects'?{projects:config.projects}:{...s,rounds,diagnosisStatus:'not-analyzed'}});w.eval(readFileSync('src/human-goal-workbench/client.js','utf8'));await new Promise(r=>setTimeout(r,40));
 try{const d=w.document;expect(d.querySelector('.round-recovery').textContent).toContain(rounds.rounds[0].sourceCoverage);expect(d.querySelector('.round-recovery').closest('details')).toBeNull();expect(d.querySelector('.round-evidence').textContent).toContain('STREAM_RECORD_LIMIT');expect(d.querySelector('.round-evidence').textContent).toContain('1048576');expect(d.querySelector('.round-evidence').textContent).toContain('recovered');expect(d.querySelector('.round-evidence').textContent).toContain('256000');expect(d.querySelector('.round-evidence').textContent).not.toContain('PRIVATE');expect(d.querySelectorAll('.scoped-check.passed')).toHaveLength(0);}finally{w.close();}
});


// Synthetic proof fixture: exercise the real persisted import and transport paths, not model quality.
async function repeatProofFixture(){
 await service.close();
 service=new HumanGoalService(config,{revision:'SYNTHETIC-repeat-proof',async analyze(input){const f=input.source.files[0],ref={path:f.path,sha256:f.sha256,start:1,end:1};return {purpose:'test',purposeRefs:[ref],limitations:[],modules:[{id:'main',title:'main',kind:'discovered',responsibility:'test',inputs:[],outputs:[],refs:[ref],supersedes:[]}],edges:[],alignments:input.goal!.clauses.map(c=>({id:`a-${c.id}`,clauseIds:[c.id],targetIds:['main'],status:'implemented-unverified',rationale:'test',refs:[ref]})),gaps:[],conflicts:[],changes:[],coverageNotes:'synthetic',feedbackResponse:'synthetic'};}});
 const r=enrollment();service.rounds.enroll('self',r);
 service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'proof-analysis'});await service.idle();
 const s=service.read('self'),v=s.views[0],record={schema:'project-os.scoped-observation.v1',producer:'synthetic-shell',sourceHash:v.source.hash,goalHash:v.goal!.hash,targetIds:['main'],clauseIds:v.goal!.clauses.map(c=>c.id),roundIds:[r.roundId],result:'passed',behaviorScope:true,invocation:{kind:'shell',argv:['synthetic-check'],stdout:'passed',stderr:'',exitCode:0}};
 const raw=JSON.stringify(record);writeFileSync(join(evidence,'proof.json'),raw);return {rootIndex:0,path:'proof.json',sha256:digest(raw)};
}
function advanceProofGeneration(){service.feedback('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'later-goal',kind:'desired-change',originalText:'A later goal must not requalify historical proof',author:'test',provenance:'synthetic',analyze:false});writeFileSync(join(source,'main.ts'),'export const later = true;');service.rounds.capture('self');}
it('literal HTTP evidence reference replays original receipt after generation advances without any new effects',async()=>{
 const ref=await repeatProofFixture();
 // In-process HTTP handler check remains separate from the required real socket test.
 vi.spyOn(Server.prototype,'listen').mockImplementation(function(this:Server,...args:any[]){queueMicrotask(()=>args.at(-1)());return this;});
 vi.spyOn(Server.prototype,'close').mockImplementation(function(this:Server,callback?:any){callback?.();return this;});
 const app=await startServer(service,9999),literal=JSON.stringify(ref);
 const post=()=>new Promise<{status:number;data:any}>(resolve=>{const req=Readable.from([Buffer.from(literal)]) as any;req.url='/api/projects/self/round-evidence';req.method='POST';req.headers={host:'127.0.0.1:9999',origin:'http://127.0.0.1:9999','content-type':'application/json'};app.server.emit('request',req,{statusCode:200,setHeader(){},end(value:string){resolve({status:this.statusCode,data:JSON.parse(value)});}});});
 try{const first=await post();expect(first.status).toBe(200);expect(first.data.qualified).toBe(true);advanceProofGeneration();const before=service.read('self'),saved=JSON.stringify(before),projection=projectRounds(before);const second=await post();expect(second.status).toBe(200);expect(second.data).toEqual(first.data);expect(JSON.stringify(service.read('self'))).toBe(saved);expect(projectRounds(service.read('self'))).toEqual(projection);expect(service.read('self').observations).toHaveLength(1);}finally{await app.close();}
});
it('offline CLI evidence replays across process reopen and later generation with the same request file',async()=>{
 const ref=await repeatProofFixture(),configPath=join(root,'config.json'),requestPath=join(root,'reference.json');writeFileSync(configPath,JSON.stringify(config));writeFileSync(requestPath,JSON.stringify(ref));await service.close();
 const run=()=>promisify(execFile)(process.execPath,['--import','tsx','scripts/project-os-rounds.ts','evidence','--config',configPath,'--project','self','--request',requestPath]);
 const first=JSON.parse((await run()).stdout);expect(first.qualified).toBe(true);
 service=new HumanGoalService(config,undefined,{dispatchRoundAnalysis:false});advanceProofGeneration();const saved=JSON.stringify(service.read('self'));await service.close();
 const second=JSON.parse((await run()).stdout);expect(second).toEqual(first);service=new HumanGoalService(config,undefined,{dispatchRoundAnalysis:false});expect(JSON.stringify(service.read('self'))).toBe(saved);expect(service.read('self').observations).toHaveLength(1);
});

it('real HTTP same-proof import returns the historical receipt after generation advances',async()=>{
 const ref=await repeatProofFixture(),app=await startServer(service),literal=JSON.stringify(ref);
 const post=()=>fetch(`${app.url}/api/projects/self/round-evidence`,{method:'POST',headers:{Origin:app.url,'Content-Type':'application/json'},body:literal});
 try{const first=await post();expect(first.status).toBe(200);const receipt=await first.json();advanceProofGeneration();const before=service.read('self');const second=await post();expect(second.status).toBe(200);expect(await second.json()).toEqual(receipt);expect(service.read('self')).toEqual(before);}finally{await app.close();}
});
