import { afterEach, expect, it } from 'vitest';
import { mkdtempSync, mkdirSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { createRequire } from 'node:module';
const {JSDOM}=createRequire(import.meta.url)('jsdom');
import { HumanGoalService } from '../../src/core/human-goal-workflow/service.js';
import { startServer } from '../../src/human-goal-workbench/server.js';
import type { AnalysisInput, Analysis } from '../../src/core/human-goal-workflow/types.js';
const cleanup:(()=>Promise<void>)[]=[];
afterEach(async()=>{for(const f of cleanup.splice(0).reverse())await f();});
async function fixture(){const root=mkdtempSync(join(tmpdir(),'closed-loop-case-'));mkdirSync(join(root,'source'));writeFileSync(join(root,'source','main.ts'),'export const main = 1;');const config={projects:[{id:'self',label:'self-case fixture',sourceRoot:join(root,'source'),scope:['main.ts'],revision:'fixture',sourceKind:'working-tree',subjectId:'self',caseRole:'self-case'}],dataDir:join(root,'data'),analyzer:{timeoutMs:null}};
 const s=new HumanGoalService(config,{revision:'case-fixture',async analyze(i:AnalysisInput):Promise<Analysis>{const f=i.source.files[0],ref={path:f.path,sha256:f.sha256,start:1,end:1};return {purpose:'read',purposeRefs:[ref],limitations:[],modules:[{id:'main',title:'Main',kind:'discovered',responsibility:'read',inputs:[],outputs:[],refs:[ref],supersedes:[]}],edges:[],alignments:[],gaps:[],conflicts:[],changes:[],coverageNotes:'fixture',feedbackResponse:'fixture',scenarios:[{id:'scenario',title:'Read current goal',given:'Saved goal',when:'Read state',then:'Original is retained',critical:'critical',clauseIds:['goal'],journeyIds:[],targetIds:['main'],mapping:'unknown',uncertainty:'Journey unknown',criteria:[{id:'criterion',text:'Goal equals saved original',observable:'GET current state',clauseIds:['goal'],journeyIds:[],targetIds:['main'],mapping:'unknown',uncertainty:'Journey unknown'}]}]};}});cleanup.push(async()=>{await s.close();rmSync(root,{recursive:true,force:true});});s.feedback('self',{expectedGeneration:0,idempotencyKey:'goal',originalText:'Preserve original',kind:'desired-change',author:'fixture',provenance:'test',clauses:[{id:'goal',text:'Preserve original',importance:'core'}]});await s.idle();return {s,config};}
function state(s:HumanGoalService){const v=s.read('self');return {...v,closedLoop:s.closedLoop('self'),rounds:{rounds:[],registrations:[],policy:{}},views:v.views.map(x=>({...x,statuses:{main:'implemented-unverified'}})),attempts:v.attempts.map(a=>({...a,goalVersion:a.input.goal?.version,plan:a.input.plan})),diagnosisStatus:'published'};}
it('real HTTP persists edited confirmation with CAS and refuses HTTP command execution',async()=>{const {s}=await fixture();const app=await startServer(s);cleanup.push(async()=>app.close());const post=(op:string,b:unknown)=>fetch(`${app.url}/api/projects/self/${op}`,{method:'POST',headers:{Origin:app.url,'Content-Type':'application/json'},body:JSON.stringify(b)});const current=s.read('self'),proposal=current.scenarioSets![0],scenarios=structuredClone(proposal.scenarios);scenarios[0].title='Owner edit';const req={expectedGeneration:current.generation,idempotencyKey:'confirm-http',proposalId:proposal.id,decision:'confirm',author:'Owner',roundId:null,scenarios,analyze:false};expect((await post('scenario-review',req)).status).toBe(200);expect((await post('scenario-review',req)).status).toBe(200);const projected:any=await(await fetch(`${app.url}/api/projects/self/state`)).json();expect(projected.closedLoop.confirmation.scenarios[0].title).toBe('Owner edit');expect(projected.closedLoop.status).toBe('incomplete');expect((await post('verification-run',{argv:['sh','-c','echo invalid']})).status).toBe(404);expect((await post('verification-import',{...req,argv:['sh']})).status).toBe(400);expect((await post('scenario-review',{...req,idempotencyKey:'stale'})).status).toBe(409);});
it('DOM offers one edited confirmation, keeps draft during polling, and exposes truthful evidence/runtime empty state',async()=>{const {s,config}=await fixture();const dom=new JSDOM(readFileSync('src/human-goal-workbench/index.html','utf8'),{url:'http://127.0.0.1:9999',runScripts:'outside-only',pretendToBeVisual:true});cleanup.push(async()=>dom.window.close());const w=dom.window as any;w.matchMedia=()=>({matches:false});w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};const posts:any[]=[];w.fetch=async(url:string,opts:any)=>{if(opts?.method==='POST'){const b=JSON.parse(opts.body);posts.push(b);if(url.endsWith('/scenario-review')){s.reviewScenarios('self',{...b,analyze:false});return {ok:true,json:async()=>({status:'confirmed'})};}}return {ok:true,json:async()=>url==='/api/projects'?{projects:config.projects}:state(s)};};w.eval(readFileSync('src/human-goal-workbench/client.js','utf8'));await new Promise(r=>setTimeout(r,50));const buttons=()=>[...w.document.querySelectorAll('button')] as any[];buttons().find(b=>b.textContent==='核对场景与条件').click();const title=w.document.querySelector('#dialog-body fieldset textarea');title.value='<img onerror=attack()> Owner edit';title.dispatchEvent(new w.Event('input'));await w.eval('refresh(true)');expect(title.value).toContain('Owner edit');buttons().find(b=>b.textContent==='确认这一组场景与条件').click();await new Promise(r=>setTimeout(r,30));expect(posts).toHaveLength(1);expect(s.read('self').scenarioSets!.at(-1)!.scenarios[0].title).toContain('Owner edit');buttons().find(b=>b.textContent==='实际验证与调用').click();expect(w.document.querySelector('#dialog-body').textContent).toContain('没有实际调用 trace');expect(w.document.querySelector('#dialog-body').textContent).toContain('未知 / 缺少条件证据');expect(w.document.querySelector('img')).toBeNull();});
import { vi } from 'vitest';
import { Server } from 'node:http';
import { Readable } from 'node:stream';
it('in-process HTTP routes expose confirmed coverage and retain CAS failures without a socket',async()=>{const {s}=await fixture();vi.spyOn(Server.prototype,'listen').mockImplementation(function(this:Server,...args:any[]){queueMicrotask(()=>args.at(-1)());return this;});vi.spyOn(Server.prototype,'close').mockImplementation(function(this:Server,cb?:any){cb?.();return this;});const app=await startServer(s,9999);try{const request=(op:string,body?:unknown)=>new Promise<{status:number;data:any}>(resolve=>{const req=Readable.from(body?[Buffer.from(JSON.stringify(body))]:[]) as any;req.url=`/api/projects/self/${op}`;req.method=body?'POST':'GET';req.headers={host:'127.0.0.1:9999',origin:'http://127.0.0.1:9999','content-type':'application/json'};app.server.emit('request',req,{statusCode:200,setHeader(){},end(value:string){resolve({status:this.statusCode,data:JSON.parse(value)});}});});const state=s.read('self'),proposal=state.scenarioSets![0],req={expectedGeneration:state.generation,idempotencyKey:'route-confirm',proposalId:proposal.id,decision:'confirm',author:'owner',roundId:null,scenarios:proposal.scenarios,analyze:false};expect((await request('scenario-review',req)).status).toBe(200);expect((await request('closed-loop')).data.criteria[0].status).toBe('unknown');expect((await request('scenario-review',{...req,idempotencyKey:'old'})).status).toBe(409);expect((await request('verification-run',{argv:['sh']})).status).toBe(404);expect((await request('verification-context?roundId=unknown')).status).toBe(409);}finally{await app.close();vi.restoreAllMocks();}});

async function domFixture(s:HumanGoalService,config:any,project=(x:any)=>x){const dom=new JSDOM(readFileSync('src/human-goal-workbench/index.html','utf8'),{url:'http://127.0.0.1:9999',runScripts:'outside-only',pretendToBeVisual:true});cleanup.push(async()=>dom.window.close());const w=dom.window as any;w.matchMedia=()=>({matches:false});w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};const posts:any[]=[];w.fetch=async(url:string,opts:any)=>{if(opts?.method==='POST'){const b=JSON.parse(opts.body);posts.push(b);try{s.reviewScenarios('self',{...b,analyze:false});return {ok:true,json:async()=>({status:'confirmed'})};}catch(e:any){return {ok:false,json:async()=>({code:e.code||'INVALID_INPUT',message:e.message})};}}return {ok:true,json:async()=>url==='/api/projects'?{projects:config.projects}:project(state(s))};};w.eval(readFileSync('src/human-goal-workbench/client.js','utf8')+'\nwindow.setHistoricalForTest = value => {historicalRound=value;renderWorkflow();renderGraph();};');await new Promise(r=>setTimeout(r,40));return {w,posts,buttons:()=>[...w.document.querySelectorAll('button')] as any[]};}
it('plain scenario/criterion add-remove survives polling, validation failure and confirmed-text reanalysis',async()=>{
 const {s,config}=await fixture(),{w,posts,buttons}=await domFixture(s,config);const click=(text:string)=>buttons().find(b=>b.textContent===text).click();click('核对场景与条件');
 expect(w.document.querySelector('#dialog-body').textContent).toContain('Preserve original');expect(w.document.querySelector('#dialog-body').textContent).toContain('Main');
 click('添加场景');expect(w.document.querySelectorAll('#dialog-body fieldset')).toHaveLength(2);buttons().filter(b=>b.textContent==='删除此场景').at(-1).click();expect(w.document.querySelectorAll('#dialog-body fieldset')).toHaveLength(1);
 click('添加验收条件');expect(w.document.querySelectorAll('.criterion-editor')).toHaveLength(2);buttons().filter(b=>b.textContent==='删除此条件').at(-1).click();
 const title=w.document.querySelector('#dialog-body fieldset textarea');title.value='';title.dispatchEvent(new w.Event('input'));click('确认这一组场景与条件');await new Promise(r=>setTimeout(r,25));expect(w.document.querySelector('#dialog').open).toBe(true);expect(w.document.querySelector('#dialog-body [role="alert"]').textContent).toContain('INVALID_INPUT');
 title.value='Human text retained';title.dispatchEvent(new w.Event('input'));await w.eval('refresh(true)');expect(title.value).toBe('Human text retained');click('确认这一组场景与条件');await new Promise(r=>setTimeout(r,25));expect(posts.at(-1).scenarios).toHaveLength(1);expect(posts.at(-1).scenarios[0].criteria).toHaveLength(1);
 s.analyze('self',{expectedGeneration:s.read('self').generation,idempotencyKey:'reanalysis'});await s.idle();await w.eval('refresh(true)');click('核对场景与条件');expect(w.document.querySelector('#dialog-body fieldset textarea').value).toBe('Human text retained');
});
it('runtime badges use explicit target/clause coverage, open exact evidence by keyboard, and isolate historical views',async()=>{
 const {s,config}=await fixture();let mode='node-only';const project=(payload:any)=>{const v=payload.views[payload.currentView],ref=v.analysis.purposeRefs[0];v.analysis.edges=[{id:'call',from:'main',to:'main',label:'Call',expected:'call',actual:'static',kind:'call',certainty:'source-supported',refs:[ref]}];v.analysis.alignments=[{id:'a',targetIds:['main','call'],clauseIds:['goal'],status:'implemented-unverified',rationale:'fixture',refs:[ref]}];
 const step=(id:string)=>({id,title:id,purpose:'Read',actor:'User',responsibility:'read',inputs:['goal'],outputs:['result'],actual:'Source support',state:'source-supported',targetIds:['main'],clauseIds:['goal'],refs:[ref],uncertainty:'Runtime separate'});
 v.analysis.workflow={status:'established',summary:'fixture',coverage:'registered-scope',unknowns:[],journeys:[{id:'journey',title:'Read',purpose:'Read goal',clauseIds:['goal'],observed:{steps:[step('start'),step('end')],links:[{id:'link',from:'start',to:'end',kind:'sequence',condition:'on read',meaning:'result',state:'source-supported',refs:[ref],targetIds:['call'],clauseIds:['goal']}]},desired:{steps:[],links:[]}}]};
 const criterion=(id:string,targets:string[],status='passed')=>({scenarioId:'scenario',scenarioTitle:'Read result',criterionId:id,text:`Condition ${id}`,observable:'Actual read',mapping:'mapped',clauseIds:['goal'],journeyIds:['journey'],targetIds:targets,status,evidence:[{receiptId:`receipt-${id}`,roundId:'round',checkId:id,at:'2026-09-22T00:00:00.000Z',status,actual:`Observation ${id}`,evidence:`Raw ${id}`,current:true}]});
 payload.closedLoop={...payload.closedLoop,sourceHash:v.source.hash,criteria:[criterion('node',['main']),...(mode==='edge'?[criterion('edge',['call'])]:mode==='mixed'?[criterion('failed',['main'],'behavior-failed')]:[])],receipts:[],runtimeCalls:[]};if(mode==='partial')v.analysis.alignments[0].clauseIds.push('uncovered');return payload;};
 const {w}=await domFixture(s,config,project),d=w.document;
 expect(d.querySelector('[data-step-id="start"] .runtime-badge').dataset.runtimeStatus).toBe('passed');expect(d.querySelector('[data-flow-link="link"] .runtime-badge').dataset.runtimeStatus).toBe('unknown');
 w.eval("setModelView('implementation')");expect(d.querySelector('[data-id="main"] .runtime-badge').dataset.runtimeStatus).toBe('passed');expect(d.querySelector('[data-id="call"] .runtime-badge').dataset.runtimeStatus).toBe('unknown');
 const b=d.querySelector('[data-id="main"] .runtime-badge');b.dispatchEvent(new w.KeyboardEvent('keydown',{key:'Enter',bubbles:true}));expect(d.querySelector('#dialog-body').textContent).toContain('Condition node');expect(d.querySelector('#dialog-body').textContent).toContain('receipt-node');expect(d.querySelector('#dialog-body').textContent).toContain('Raw node');expect(d.querySelector('#dialog-body').textContent).not.toContain('Condition edge');d.querySelector('#close-dialog').click();
 mode='edge';await w.eval('refresh(true)');expect(d.querySelector('[data-flow-link="link"] .runtime-badge').dataset.runtimeStatus).toBe('passed');
 mode='partial';await w.eval('refresh(true)');expect(d.querySelector('[data-id="main"] .runtime-badge').dataset.runtimeStatus).toBe('partial');
 mode='mixed';await w.eval('refresh(true)');expect(d.querySelector('[data-id="main"] .runtime-badge').dataset.runtimeStatus).toBe('mixed');
 w.setHistoricalForTest('historical');const historical=d.querySelector('[data-step-id="start"] .runtime-badge');expect(historical.dataset.runtimeStatus).toBe('unavailable');historical.dispatchEvent(new w.KeyboardEvent('keydown',{key:' ',bubbles:true}));expect(d.querySelector('#dialog-body').textContent).toContain('历史或过时图不使用当前目标的运行证据');expect(d.querySelector('#dialog-body').textContent).not.toContain('receipt-node');
});

it('shows uncovered goals and lets a user supplement proposals without replacing confirmed wording',async()=>{
 const {s,config}=await fixture();
 s.feedback('self',{expectedGeneration:s.read('self').generation,idempotencyKey:'expanded-goal',originalText:'Preserve original and report changes',kind:'desired-change',author:'fixture owner',provenance:'synthetic test',clauses:[{id:'goal',text:'Preserve original',importance:'core'},{id:'changes',text:'Report changes',importance:'core'}]});await s.idle();
 const current=s.read('self'),proposal=current.scenarioSets!.at(-1)!;
 proposal.scenarios.push({...structuredClone(proposal.scenarios[0]),id:'changes-scenario',title:'Review actual changes',clauseIds:['changes'],criteria:[{...structuredClone(proposal.scenarios[0].criteria[0]),id:'changes-criterion',clauseIds:['changes'],text:'Actual changes are visible'}]});s.store.save(current);
 const confirmed=structuredClone(proposal.scenarios.slice(0,1));confirmed[0].title='Human wording retained';
 s.reviewScenarios('self',{expectedGeneration:current.generation,idempotencyKey:'partial-confirm',proposalId:proposal.id,decision:'confirm',author:'fixture owner',roundId:null,scenarios:confirmed,analyze:false});
 const {w,buttons,posts}=await domFixture(s,config),click=(name:string)=>{const b=buttons().find(b=>b.textContent===name);expect(b).toBeTruthy();b.click();};
 click('核对场景与条件');
 expect(w.document.querySelector('#scenario-coverage').textContent).toContain('Report changes：未设关键条件');
 click('补入草稿：Review actual changes');
 expect(posts).toHaveLength(0);
 expect(w.document.querySelector('#scenario-coverage').textContent).toContain('Report changes：已有条件，映射待核对');
 expect(w.document.querySelector('#dialog-body fieldset textarea').value).toBe('Human wording retained');
 await w.eval('refresh(true)');
 expect(w.document.querySelectorAll('#dialog-body fieldset')).toHaveLength(2);
 click('确认这一组场景与条件');await new Promise(r=>setTimeout(r,30));
 expect(posts.at(-1).scenarios.map((x:any)=>x.title)).toEqual(['Human wording retained','Review actual changes']);
 expect(s.read('self').scenarioSets!.filter(x=>x.status==='confirmed')).toHaveLength(2);
 expect(s.closedLoop('self').status).not.toBe('verified');
});

it('offers changed same-ID proposals as separate drafts without replacing the human scenario',async()=>{
 const {s,config}=await fixture();let current=s.read('self');const proposal=current.scenarioSets![0];
 s.reviewScenarios('self',{expectedGeneration:current.generation,idempotencyKey:'same-id-confirm',proposalId:proposal.id,decision:'confirm',author:'fixture owner',roundId:null,scenarios:proposal.scenarios,analyze:false});
 current=s.read('self');current.scenarioSets![0].scenarios[0].then='New proposed outcome';current.scenarioSets![0].scenarios[0].criteria[0].text='New meaning under the same ID';s.store.save(current);
 const {w,buttons,posts}=await domFixture(s,config);buttons().find(b=>b.textContent==='核对场景与条件').click();
 expect(w.document.querySelector('#dialog-body').textContent).toContain('同 ID 提议有变化');
 const add=buttons().find(b=>b.textContent==='另存为补充草稿：Read current goal');expect(add).toBeTruthy();add.click();
 expect(w.document.querySelectorAll('#dialog-body fieldset')).toHaveLength(2);
 expect(buttons().filter(b=>b.textContent==='另存为补充草稿：Read current goal')).toHaveLength(0);
 buttons().find(b=>b.textContent==='确认这一组场景与条件').click();await new Promise(r=>setTimeout(r,30));
 const scenarios=posts.at(-1).scenarios;expect(scenarios[0].then).toBe('Original is retained');expect(scenarios[1].then).toBe('New proposed outcome');
 const ids=scenarios.flatMap((x:any)=>[x.id,...x.criteria.map((c:any)=>c.id)]);expect(new Set(ids).size).toBe(ids.length);
});
