import { afterEach, beforeEach, expect, it } from 'vitest';
import { appendFileSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { HumanGoalService } from '../../src/core/human-goal-workflow/service.js';
import { analysisRoundContext, projectRounds, roundData, type Enrollment } from '../../src/core/human-goal-workflow/rounds.js';
import { digest, type Analysis, type AnalysisInput } from '../../src/core/human-goal-workflow/types.js';
import { createRequire } from 'node:module';
import { startServer } from '../../src/human-goal-workbench/server.js';
const {JSDOM}=createRequire(import.meta.url)('jsdom');

let root:string, source:string, evidence:string, config:any, service:HumanGoalService;
const model={revision:'SYNTHETIC-recovery-attribution',async analyze(input:AnalysisInput):Promise<Analysis>{const f=input.source.files[0],ref={path:f.path,sha256:f.sha256,start:1,end:1};return {purpose:'synthetic source fixture',purposeRefs:[ref],limitations:[],modules:[{id:'main',title:'main',kind:'discovered',responsibility:'main',inputs:[],outputs:[],refs:[ref],supersedes:[]}],edges:[],alignments:input.goal!.clauses.map(c=>({id:`a-${c.id}`,clauseIds:[c.id],targetIds:['main'],status:'implemented-unverified',rationale:'fixture source',refs:[ref]})),gaps:[],conflicts:[],changes:[],coverageNotes:'fixture only',feedbackResponse:'fixture only'};}};
const line=(value:unknown)=>JSON.stringify(value)+'\n';
beforeEach(()=>{root=mkdtempSync(join(tmpdir(),'recovery-attribution-'));source=join(root,'source');evidence=join(root,'evidence');mkdirSync(source);mkdirSync(evidence);writeFileSync(join(source,'main.ts'),'export const main = 1;\n');writeFileSync(join(evidence,'selected.jsonl'),'');config={projects:[{id:'self',label:'synthetic recovery',sourceRoot:source,scope:['.'],revision:'fixture',sourceKind:'working-tree',subjectId:'self',caseRole:'self-case',evidenceRoots:[evidence]}],dataDir:join(root,'data'),analyzer:{timeoutMs:null}};service=new HumanGoalService(config,model,{dispatchRoundAnalysis:false});service.feedback('self',{expectedGeneration:0,idempotencyKey:'goal',kind:'desired-change',originalText:'Attribute proof to the actual development round',author:'test',provenance:'synthetic',clauses:[{id:'goal',text:'Attribute proof to the actual development round',importance:'core'}],analyze:false});});
afterEach(async()=>{await service.close();rmSync(root,{recursive:true,force:true});});
function connect(){return service.activity.connect('self',{id:'connection',projectId:'self',repoRoot:source,worktreeRoot:source,branch:'fixture',format:'codex-exec-jsonl',toolVersion:'0.155.0-alpha.9.2',taskId:'task',goalHash:service.read('self').goals[0].hash,purpose:'Observe actual round progress',clauseIds:['goal'],journeyIds:[],selectedActionIds:[],stream:{rootIndex:0,path:'selected.jsonl'},start:'from-now'});}
async function analyze(){service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'proof-view'});await service.idle();}
function observe(key:string,roundIds?:string[]){const s=service.read('self'),record={schema:'project-os.scoped-observation.v1',producer:'synthetic-shell',sourceHash:s.views.at(-1)!.source.hash,goalHash:s.goals[0].hash,targetIds:['main'],clauseIds:['goal'],...(roundIds?{roundIds}:{}),result:'passed',behaviorScope:true,scopeSummary:'Synthetic round attribution check',limitations:['No real model or human acceptance'],invocation:{kind:'shell',argv:['synthetic-check'],stdout:'passed',stderr:'',exitCode:0}},rawRecord=JSON.stringify(record),path=`${key}.json`;writeFileSync(join(evidence,path),rawRecord);const result=service.observe('self',{expectedGeneration:s.generation,idempotencyKey:key,producer:record.producer,rawRecord,rawHash:digest(rawRecord),sourceHash:record.sourceHash,goalHash:record.goalHash,targetIds:record.targetIds,clauseIds:record.clauseIds,result:'passed',trustedRecord:{rootIndex:0,path}}) as {qualified:boolean;observationId:string};expect(result.qualified).toBe(true);return result.observationId;}

it('observer replay keeps old source timing and excludes later or unscoped proof while same-round proof remains usable',async()=>{
 connect();const path=join(evidence,'selected.jsonl'),prefix=[{type:'thread.started',thread_id:'thread'},{type:'turn.started',turn_id:'old'}].map(line).join('');appendFileSync(path,prefix+'{invalid}\n');const failed=service.activity.poll('self','connection');expect(failed.issue).toContain('STREAM_SCHEMA');const original=structuredClone(roundData(service.read('self')).events);
 writeFileSync(join(source,'main.ts'),'export const later = 2;\n');writeFileSync(path,prefix+line({type:'turn.completed',turn_id:'old'}));const recovered=service.activity.replay('self','connection');expect(recovered.status).toBe('caught-up');const old=projectRounds(service.read('self')).rounds[0];
 appendFileSync(path,[{type:'turn.started',turn_id:'later'},{type:'turn.completed',turn_id:'later'}].map(line).join(''));service.activity.poll('self','connection');await analyze();const current=projectRounds(service.read('self')).rounds[1];expect(current.after!.sourceHash).toBe(old.after!.sourceHash);
 const later=observe('later-proof',[current.id]),global=observe('global-proof'),same=observe('same-round-proof',[old.id]);let s=service.read('self'),rounds=projectRounds(s).rounds;
 expect.soft(rounds[0].verified.map(x=>x.id)).toEqual([same]);expect.soft(rounds[0].evidenceCount).toBe(1);expect.soft(rounds[0].delayedRecovery).toBe(true);expect.soft(rounds[1].verified.map(x=>x.id)).toEqual([later,global]);expect.soft(rounds[1].delayedRecovery).toBe(false);
 expect.soft(s.rounds!.events.find(x=>x.event.roundId===old.id&&x.event.kind==='completed')!.event.sourceTiming).toBe('recovery-read-time');expect(s.rounds!.events.slice(0,original.length)).toEqual(original);expect(s.agentActivity!.connections[0].history.map(x=>x.kind)).toEqual(['error','replay','recovered']);expect.soft((rounds[0] as any).recoveryStatus).toBe('recovered');
 const saved=JSON.stringify(s);await service.close();service=new HumanGoalService(config,model,{dispatchRoundAnalysis:false});s=service.read('self');expect(JSON.stringify(s)).toBe(saved);expect(projectRounds(s).rounds.map(r=>r.verified.map(x=>x.id))).toEqual([[same],[later,global]]);expect(JSON.stringify(analysisRoundContext(s))).toContain('recovery-read-time');
});

it('observer recovery range survives a batch restart and ends before a new live round',async()=>{
 connect();const path=join(evidence,'selected.jsonl'),prefix=[{type:'thread.started',thread_id:'thread'},{type:'turn.started',turn_id:'old'}].map(line).join('');appendFileSync(path,prefix+'{invalid}\n');expect(service.activity.poll('self','connection').status).toBe('sync-error');
 const tools=Array.from({length:18},(_,i)=>({type:'item.completed',item:{id:`tool-${i}`,type:'command_execution',command:'synthetic',aggregated_output:'',status:'completed',exit_code:0}}));writeFileSync(path,prefix+tools.map(line).join('')+line({type:'turn.completed',turn_id:'old'}));const first=service.activity.replay('self','connection');expect(first.status).toBe('following');expect.soft(first.history.map(x=>x.kind)).toEqual(['error','replay']);expect.soft((projectRounds(service.read('self')).rounds[0] as any).recoveryStatus).toBe('reading');
 appendFileSync(path,[{type:'turn.started',turn_id:'fresh'},{type:'turn.completed',turn_id:'fresh'}].map(line).join(''));
 await service.close();service=new HumanGoalService(config,model,{dispatchRoundAnalysis:false});for(let i=0;i<4;i++)service.activity.poll('self','connection');const s=service.read('self'),r=projectRounds(s).rounds[0];expect.soft(r.delayedRecovery).toBe(true);expect(s.agentActivity!.connections[0].status).toBe('caught-up');expect(s.agentActivity!.connections[0].history.map(x=>x.kind)).toEqual(['error','replay','recovered']);expect(s.rounds!.events.filter(x=>x.event.roundId===r.id)).toHaveLength(20);expect.soft(s.rounds!.events.filter(x=>x.event.roundId===r.id).slice(1).every(x=>x.event.sourceTiming==='recovery-read-time')).toBe(true);
 expect.soft((r as any).recoveryStatus).toBe('recovered');const fresh=projectRounds(service.read('self')).rounds[1];expect(fresh.delayedRecovery).toBe(false);expect(service.read('self').rounds!.events.filter(x=>x.event.roundId===fresh.id).every(x=>!x.event.sourceTiming)).toBe(true);
});

it('sourceTiming alone protects legacy history without rewriting its original event or registration',async()=>{
 const s=service.read('self'),before=service.rounds.capture('self'),r:Enrollment={id:'old',projectId:'self',repoRoot:source,worktreeRoot:source,branch:'fixture',tool:'codex-exec',toolVersion:'0.155.0-alpha.9.2',taskId:'task',roundId:'old',attemptId:'attempt',producerId:'producer',mode:'live',goalHash:s.goals[0].hash,feedbackIds:[],purpose:'fixture',clauseIds:['goal'],journeyIds:[],selectedActionIds:[],acceptedPlan:null,beforeSnapshotId:before.id,stream:{rootIndex:0,path:'manual.jsonl'},deferredBenefit:null};service.rounds.enroll('self',r);
 service.rounds.accept('self',{key:'begin',projectId:'self',registrationId:r.id,roundId:r.roundId,attemptId:r.attemptId,producerId:r.producerId,sequence:1,dependsOn:[],kind:'begin',description:'turn-start',rawHash:digest('begin'),observedAt:new Date().toISOString(),sourceSnapshotId:null});const after=service.rounds.capture('self');service.rounds.accept('self',{key:'completed',projectId:'self',registrationId:r.id,roundId:r.roundId,attemptId:r.attemptId,producerId:r.producerId,sequence:2,dependsOn:[],kind:'completed',description:'turn-completed',rawHash:digest('completed'),observedAt:new Date().toISOString(),sourceSnapshotId:after.id,sourceTiming:'recovery-read-time'});
 const legacy=service.read('self');delete legacy.rounds!.registrations[0].delayedRecovery;service.store.save(legacy);await analyze();observe('unscoped');const actual=service.read('self'),original=JSON.stringify(actual.rounds),projection=projectRounds(actual);
 expect(projection.rounds[0].delayedRecovery).toBe(true);expect.soft((projection.rounds[0] as any).recoveryStatus).toBe('unknown');expect(projection.rounds[0].verified).toEqual([]);expect(projection.rounds[0].evidenceCount).toBe(0);expect(analysisRoundContext(actual).registrations[0].delayedRecovery).toBe(true);expect(JSON.stringify(actual.rounds)).toBe(original);expect(readFileSync(join(evidence,'unscoped.json'),'utf8')).toContain('Synthetic round attribution check');
});

it('normal HTTP projection tells the round page reception recovered while keeping historical source limits',async()=>{
 connect();const path=join(evidence,'selected.jsonl'),prefix=[{type:'thread.started',thread_id:'thread'},{type:'turn.started',turn_id:'old'}].map(line).join('');writeFileSync(path,prefix+'{invalid}\n');expect(service.activity.poll('self','connection').status).toBe('sync-error');writeFileSync(path,prefix+line({type:'turn.completed',turn_id:'old'}));service.activity.replay('self','connection');await analyze();const app=await startServer(service);const dom=new JSDOM(readFileSync('src/human-goal-workbench/index.html','utf8'),{url:app.url,runScripts:'outside-only',pretendToBeVisual:true}),w=dom.window;
 try{w.matchMedia=(()=>({matches:false})) as any;w.HTMLDialogElement.prototype.showModal=function(){this.open=true;};w.HTMLDialogElement.prototype.close=function(){this.open=false;};w.fetch=((url:string,options:any)=>fetch(app.url+url,{...options,headers:{...options?.headers,Origin:app.url}})) as any;w.eval(readFileSync('src/human-goal-workbench/client.js','utf8'));await new Promise(r=>setTimeout(r,90));w.document.getElementById('tab-rounds')!.click();const text=w.document.querySelector('.round-recovery')?.textContent;expect.soft(text).toContain('事件接收已恢复');expect(text).toContain('历史源码覆盖和命令归因未知');expect(text).not.toContain('恢复尚未完成');}finally{dom.window.close();await app.close();}
});
