import { afterEach, beforeEach, it, expect, vi } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, appendFileSync, readFileSync, rmSync, renameSync, symlinkSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { HumanGoalService, targetStatus } from '../../src/core/human-goal-workflow/service.js';
import { projectRounds, roundData, sourceDelta, currentAnalysisRoundContext, type Enrollment, type RoundEvent } from '../../src/core/human-goal-workflow/rounds.js';
import { normalizeCodex } from '../../src/core/human-goal-workflow/codex-events.js';
import { digest, hash, type AnalysisInput, type Analysis } from '../../src/core/human-goal-workflow/types.js';
import { discoverSource } from '../../src/core/human-goal-workflow/source.js';
import { validateAnalysis, outputSchema, makePrompt } from '../../src/core/human-goal-workflow/analyzer.js';
let root:string,source:string,evidence:string,service:HumanGoalService,config:any;
const model={revision:'SYNTHETIC-rounds',async analyze(input:AnalysisInput):Promise<Analysis>{const f=input.source.files[0],ref={path:f.path,sha256:f.sha256,start:1,end:1};return {purpose:'synthetic code understanding',purposeRefs:[ref],limitations:[],modules:[{id:'main',title:'main',kind:'discovered',responsibility:'main',inputs:[],outputs:[],refs:[ref],supersedes:[]}],edges:[],alignments:input.goal?.clauses.map(c=>({id:`a-${c.id}`,clauseIds:[c.id],targetIds:['main'],status:'implemented-unverified',rationale:'source',refs:[ref]}))??[],gaps:[],conflicts:[],changes:[],coverageNotes:'test only',feedbackResponse:'test only'};}};
beforeEach(()=>{root=mkdtempSync(join(tmpdir(),'rounds-SYNTHETIC-'));source=join(root,'source');evidence=join(root,'evidence');mkdirSync(source);mkdirSync(evidence);writeFileSync(join(source,'main.ts'),'export const main = 1;\n');config={projects:[{id:'self',label:'synthetic',sourceRoot:source,scope:['.'],revision:'test',sourceKind:'working-tree',subjectId:'self',caseRole:'self-case',evidenceRoots:[evidence]}],dataDir:join(root,'data'),analyzer:{timeoutMs:null}};service=new HumanGoalService(config,model);service.feedback('self',{expectedGeneration:0,idempotencyKey:'goal',kind:'desired-change',originalText:'Observe actual progress',author:'test',provenance:'synthetic',clauses:[{id:'goal',text:'actual progress',importance:'core'}],analyze:false});});
afterEach(async()=>{vi.restoreAllMocks();await service.close();rmSync(root,{recursive:true,force:true});});
function registration(id='r1',mode:'live'|'historical-replay'='live'):Enrollment {const s=service.read('self'),before=service.rounds.capture('self');return {id,projectId:'self',repoRoot:source,worktreeRoot:source,branch:'test',tool:'codex-exec',toolVersion:'0.155.0-alpha.2.6',taskId:`task-${id}`,roundId:`round-${id}`,attemptId:`attempt-${id}`,producerId:`producer-${id}`,mode,goalHash:s.goals.at(-1)!.hash,feedbackIds:[s.feedback[0].id],purpose:'test real changes',clauseIds:['goal'],journeyIds:[],selectedActionIds:[],acceptedPlan:null,beforeSnapshotId:before.id,stream:{rootIndex:0,path:`${id}.jsonl`},deferredBenefit:null};}
function event(r:Enrollment,n:number,extra:Partial<RoundEvent>={}):RoundEvent{return {key:`${r.id}-e${n}`,projectId:'self',registrationId:r.id,roundId:r.roundId,attemptId:r.attemptId,producerId:r.producerId,sequence:n,dependsOn:[],kind:n===1?'begin':'checkpoint',description:n===1?'turn-start':'activity-observed',rawHash:digest(`event-${n}`),observedAt:'2026-09-17T00:00:00.000Z',sourceSnapshotId:null,...extra};}
function lines(id:string,values:unknown[]){writeFileSync(join(evidence,`${id}.jsonl`),values.map(x=>JSON.stringify(x)).join('\n')+'\n');}
it('current analysis supplies recent goal rounds and dependencies while retaining older history explicitly',()=>{
 for(let n=0;n<6;n++){const r=registration(`context-${n}`);service.rounds.enroll('self',r);service.rounds.accept('self',event(r,1));service.rounds.accept('self',event(r,2,{kind:'completed',description:'turn-completed',sourceSnapshotId:service.rounds.capture('self').id}));}
 const state=service.read('self'),before=JSON.stringify(state),context=currentAnalysisRoundContext(state,{window:3,noProofThreshold:3,addedBytesThreshold:20000});
 expect(context.registrations.map(r=>r.binding.id)).toEqual(['context-3','context-4','context-5']);
 expect(context.events).toHaveLength(6);expect(context.history.archivedRounds).toHaveLength(3);
 expect(context.history).toMatchObject({mode:'current-goal-window',totalEvents:12,suppliedEvents:6});
 expect(context.history.archivedRounds.every(r=>r.contentHash.length===64&&r.eventCount===2)).toBe(true);
 expect(JSON.stringify(state)).toBe(before);
 state.rounds!.events.at(-1)!.event.dependsOn=['context-0-e1'];
 const linked=currentAnalysisRoundContext(state,{window:3,noProofThreshold:3,addedBytesThreshold:20000});
 expect(linked.registrations.map(r=>r.binding.id)).toEqual(['context-0','context-3','context-4','context-5']);
 expect(linked.events.some(e=>e.key==='context-0-e1')).toBe(true);
});
// Device migration is simulated in the saved identity; inode replacement uses a
// real rename and new file. Both retain the actual consumed bytes and receipts.
it.each(['device','inode'])('exact terminal archive recovery after %s change preserves history and is idempotent across restart',async(change)=>{
 const r=registration();service.rounds.enroll('self',r);lines(r.id,[{type:'turn.started'},{type:'turn.completed'}]);
 const terminal=service.follower.follow('self',r.id),path=join(evidence,'r1.jsonl'),raw=readFileSync(path);
 if(change==='device'){const [dev,ino]=terminal.fileIdentity!.split(':');service.rounds.update('self',r.id,{fileIdentity:`${Number(dev)+1}:${ino}`});}
 else {renameSync(path,join(evidence,'original.jsonl'));writeFileSync(path,raw);}
 const before=service.read('self'),object=join(config.dataDir,'sessions','self',`${hash(before)}.json`),original=readFileSync(object);
 const failed=service.follower.follow('self',r.id);expect(failed.issue).toContain('STREAM_ROTATED');
 service.follower.poll();expect(roundData(service.read('self')).registrations[0]).toEqual(failed);
 await service.close();service=new HumanGoalService(config,model);
 const capture=vi.spyOn(service.rounds,'capture'),accept=vi.spyOn(service.rounds,'accept'),analyze=vi.spyOn(model,'analyze');
 const recovered=service.follower.follow('self',r.id);expect(recovered.status).toBe('terminal');expect(recovered.issue).toBeNull();
 expect(recovered).toMatchObject({offset:terminal.offset,line:terminal.line,cursor:terminal.cursor,prefixHash:terminal.prefixHash,binding:terminal.binding,lastReceivedAt:terminal.lastReceivedAt});
 expect(recovered.fileIdentity).not.toBe(failed.fileIdentity);
 expect(recovered.syncHistory?.map(e=>e.kind)).toEqual(['error','replay','recovered']);
 expect(recovered.syncHistory?.[0]).toEqual(failed.syncHistory?.[0]);
 expect(recovered.syncHistory?.every(e=>e.offset===terminal.offset&&e.cursor===terminal.cursor&&e.prefixHash===terminal.prefixHash)).toBe(true);
 await service.idle();expect(capture).not.toHaveBeenCalled();expect(accept).not.toHaveBeenCalled();expect(analyze).not.toHaveBeenCalled();
 const after=service.read('self');expect(after.rounds!.events).toEqual(before.rounds!.events);expect(after.rounds!.snapshots).toEqual(before.rounds!.snapshots);expect(after.observations).toEqual(before.observations);expect(after.attempts).toEqual(before.attempts);expect(readFileSync(object)).toEqual(original);
 const save=vi.spyOn(service.store,'save');service.follower.follow('self',r.id);service.follower.poll();expect(save).not.toHaveBeenCalled();
 await service.close();service=new HumanGoalService(config,model);service.follower.follow('self',r.id);expect(service.read('self')).toEqual(after);
});
it.each(['same-size tamper','shorter','appended','unfinished','pending','unconsumed terminal','empty'])('exact terminal archive recovery rejects %s without importing progress',(variant)=>{
 const r=registration();service.rounds.enroll('self',r);
 if(variant==='empty')writeFileSync(join(evidence,'r1.jsonl'),'');
 else lines(r.id,variant==='unfinished'?[{type:'turn.started'}]:[{type:'turn.started'},{type:'turn.completed'}]);
 const consumed=service.follower.follow('self',r.id),path=join(evidence,'r1.jsonl'),raw=readFileSync(path,'utf8');
 if(variant==='pending')service.rounds.accept('self',event(r,3,{dependsOn:['absent']}));
 if(variant==='unconsumed terminal')service.rounds.update('self',r.id,{cursor:1});
 renameSync(path,join(evidence,'original.jsonl'));
 writeFileSync(path,variant==='same-size tamper'?raw.replace('turn.started','turn.changed'):variant==='shorter'?raw.slice(0,-1):variant==='appended'?raw+'{"type":"turn.started"}\n':raw);
 const before=service.read('self'),capture=vi.spyOn(service.rounds,'capture'),accept=vi.spyOn(service.rounds,'accept');
 expect(service.follower.follow('self',r.id).issue).toContain('STREAM_ROTATED');
 const failed=service.follower.follow('self',r.id);expect(failed.status).toBe('sync-error');expect(failed.issue).not.toBeNull();
 expect(failed).toMatchObject({offset:consumed.offset,line:consumed.line,prefixHash:consumed.prefixHash,fileIdentity:consumed.fileIdentity});
 expect(failed.syncHistory?.some(e=>e.kind==='recovered')).toBe(false);expect(capture).not.toHaveBeenCalled();expect(accept).not.toHaveBeenCalled();
 expect(service.read('self').rounds!.events).toEqual(before.rounds!.events);expect(service.read('self').rounds!.snapshots).toEqual(before.rounds!.snapshots);
 const stopped=service.read('self');service.follower.poll();expect(service.read('self')).toEqual(stopped);
});
it('durable ACK, exact duplicate, immutable conflict, out-of-order gap and dependency release survive reopen',async()=>{const r=registration();service.rounds.enroll('self',r);const third=event(r,3,{dependsOn:['r1-e2']});expect(service.rounds.accept('self',third).cursor).toBe(0);expect(service.rounds.accept('self',event(r,1)).cursor).toBe(1);expect(projectRounds(service.read('self')).rounds[0].pending).toHaveLength(1);expect(service.rounds.accept('self',event(r,2)).cursor).toBe(3);expect(service.rounds.accept('self',third).duplicate).toBe(true);expect(()=>service.rounds.accept('self',{...third,rawHash:digest('changed')})).toThrow('冲突');expect(()=>service.rounds.accept('self',{...third,key:'another'})).toThrow('冲突');await service.close();service=new HumanGoalService(config,model);const d=roundData(service.read('self'));expect(d.events).toHaveLength(3);expect(d.conflicts).toHaveLength(2);expect(d.registrations[0].cursor).toBe(3);});
it('per producer cursors do not overwrite and cross producer dependencies wait',()=>{const a=registration('a'),b=registration('b');service.rounds.enroll('self',a);service.rounds.enroll('self',b);service.rounds.accept('self',event(b,1,{dependsOn:['a-e1']}));expect(roundData(service.read('self')).registrations[1].cursor).toBe(0);service.rounds.accept('self',event(a,1));expect(roundData(service.read('self')).registrations.map(r=>r.cursor)).toEqual([1,1]);});
it('no ACK is returned on failed durable save; replay after committed lost ACK is idempotent',()=>{const r=registration();service.rounds.enroll('self',r);const save=vi.spyOn(service.store,'save').mockImplementationOnce(()=>{throw new Error('injected disk failure');});expect(()=>service.rounds.accept('self',event(r,1))).toThrow('disk failure');expect(roundData(service.read('self')).events).toHaveLength(0);save.mockRestore();service.rounds.accept('self',event(r,1));expect(service.rounds.accept('self',event(r,1)).duplicate).toBe(true);});
it('records uncommitted source, document, config additions/deletions and rollback without claiming progress',()=>{const before=service.rounds.capture('self');writeFileSync(join(source,'main.ts'),'export const main = 2;\n');writeFileSync(join(source,'notes.md'),'notes');writeFileSync(join(source,'config.json'),'{}');const after=service.rounds.capture('self');expect(sourceDelta(before,after).map(x=>x.path)).toEqual(['config.json','main.ts','notes.md']);rmSync(join(source,'notes.md'));expect(sourceDelta(after,service.rounds.capture('self')).some(x=>x.kind==='deleted')).toBe(true);writeFileSync(join(source,'main.ts'),'export const main = 1;\n');expect(sourceDelta(after,service.rounds.capture('self')).some(x=>x.path==='main.ts')).toBe(true);});
it('partial lines are retained; append resumes without duplicate; prefix tampering fails closed',()=>{const r=registration();service.rounds.enroll('self',r);writeFileSync(join(evidence,'r1.jsonl'),'{"type":"turn.started"');expect(service.follower.follow('self','r1').status).toBe('partial-line');expect(roundData(service.read('self')).events).toHaveLength(0);appendFileSync(join(evidence,'r1.jsonl'),'}\n');service.follower.follow('self','r1');service.follower.follow('self','r1');expect(roundData(service.read('self')).events).toHaveLength(1);writeFileSync(join(evidence,'r1.jsonl'),'{"type":"turn.failed "}\n');expect(service.follower.follow('self','r1').issue).toContain('STREAM_CHANGED');});
it('restart replays a saved event whose file offset was not ACKed without resnapshotting',async()=>{const r=registration();service.rounds.enroll('self',r);lines('r1',[{type:'turn.started'}]);service.follower.follow('self','r1');const count=roundData(service.read('self')).snapshots.length;service.rounds.update('self','r1',{offset:0,line:0,prefixHash:digest('')});await service.close();service=new HumanGoalService(config,model);service.follower.follow('self','r1');expect(roundData(service.read('self')).snapshots).toHaveLength(count);expect(roundData(service.read('self')).events).toHaveLength(1);});
it('truncation, rotation, invalid JSON and oversized lines are explicit failures, never silently skipped',()=>{const r=registration();service.rounds.enroll('self',r);lines('r1',[{type:'turn.started'}]);service.follower.follow('self','r1');writeFileSync(join(evidence,'r1.jsonl'),'');expect(service.follower.follow('self','r1').issue).toContain('TRUNCATED');renameSync(join(evidence,'r1.jsonl'),join(evidence,'old'));lines('r1',[{type:'turn.started'}]);expect(service.follower.follow('self','r1').issue).toContain('ROTATED');const b=registration('b');service.rounds.enroll('self',b);writeFileSync(join(evidence,'b.jsonl'),'invalid\n');expect(service.follower.follow('self','b').issue).toContain('SCHEMA');writeFileSync(join(evidence,'b.jsonl'),'x'.repeat(256001));expect(service.follower.follow('self','b').issue).toContain('LIMIT');});
it('historical replay never fabricates an end snapshot and never exposes raw chat, reasoning or secret commands',()=>{const r=registration('r1','historical-replay');service.rounds.enroll('self',r);lines('r1',[{type:'thread.started',thread_id:'t'},{type:'turn.started'},{type:'item.completed',item:{id:'a',type:'agent_message',text:'SECRET reported fixed'}},{type:'item.completed',item:{id:'b',type:'command_execution',command:'SECRET'}},{type:'item.completed',item:{id:'c',type:'reasoning',text:'SECRET'}},{type:'turn.completed',usage:{}}]);service.follower.follow('self','r1');const p=projectRounds(service.read('self'));expect(p.rounds[0].after).toBeNull();expect(p.rounds[0].verified).toHaveLength(0);expect(p.rounds[0].reported).toContain('不等于');expect(JSON.stringify(service.read('self').rounds)).not.toContain('SECRET');expect(p.registrations[0].connected).toBe(false);});
it('missing producer, unsupported version and second turn cannot appear automatically connected',()=>{const r=registration();service.rounds.enroll('self',r);expect(service.follower.follow('self','r1').status).toBe('waiting');lines('r1',[{type:'turn.started'},{type:'turn.completed'},{type:'turn.started'}]);expect(service.follower.follow('self','r1').issue).toContain('ROUND_BOUNDARY');const b=registration('b');expect(service.rounds.enroll('self',{...b,toolVersion:'unverified'}).status).toBe('unsupported');expect(()=>normalizeCodex({type:'unknown'})).toThrow();});
it('rejects cross-project identity, symlink and traversal, stale goals and stale live baseline',()=>{const r=registration();expect(()=>service.rounds.enroll('self',{...r,projectId:'another'})).toThrow();expect(()=>service.rounds.enroll('self',{...r,stream:{rootIndex:0,path:'../outside'}})).toThrow();symlinkSync(join(source,'main.ts'),join(evidence,'link'));expect(()=>service.rounds.enroll('self',{...r,stream:{rootIndex:0,path:'link'}})).toThrow();writeFileSync(join(source,'main.ts'),'changed');expect(()=>service.rounds.enroll('self',r)).toThrow('live');expect(()=>service.rounds.enroll('self',{...r,goalHash:digest('wrong')})).toThrow('目标');});
it('goal correction preserves a running task while making relevance stale',()=>{const r=registration();service.rounds.enroll('self',r);service.rounds.accept('self',event(r,1));const s=service.read('self');service.feedback('self',{expectedGeneration:s.generation,idempotencyKey:'g2',originalText:'Corrected intention',kind:'desired-change',author:'user',provenance:'test',analyze:false});const round=projectRounds(service.read('self')).rounds[0];expect(round.stale).toBe(true);expect(round.status).toBe('running');expect(round.goalHash).toBe(r.goalHash);});
it('imports exact parent preflight without resnapshotting and preserves unknown capture time and untracked coverage',()=>{const input={sourceRoot:source,trackedHashes:{'main.ts':digest('earlier source')},head:'old',deliverables:[]},bytes=JSON.stringify(input);writeFileSync(join(evidence,'preflight.json'),bytes);const snap=service.rounds.importSnapshot('self',{rootIndex:0,path:'preflight.json',sha256:digest(bytes)});expect(snap.inventory[0].sha256).toBe(digest('earlier source'));expect(snap.observedAt).toBeNull();expect(snap.partial).toBe(true);expect(service.rounds.importSnapshot('self',{rootIndex:0,path:'preflight.json',sha256:digest(bytes)}).id).toBe(snap.id);});
it('overall diagnosis permits goal journeys without forced module gap and validates every source join',async()=>{service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'analyze'});await service.idle();const input=service.read('self').attempts[0].input,raw=await model.analyze(input),ref=raw.purposeRefs[0];raw.diagnosis={scope:'product',certainty:'supported-hypothesis',scopeReason:'combined journey unknown',conclusion:'integration requires evidence',clauseIds:['goal'],journeys:[{id:'journey',title:'whole journey',clauseIds:['goal'],targetIds:[],expected:'complete',actual:'unobserved',uncertainty:'runtime',refs:[ref]}],evidence:[ref],counterEvidence:[],alternatives:[{explanation:'missing observation',refs:[ref],discriminatingObservation:'run journey'}],recommendation:{action:'observe journey',reason:'combination evidence missing',kind:'investigate',clauseIds:['goal'],journeyIds:['journey'],targetIds:[],options:[{disposition:'reuse',subject:'main',reason:'source exists'}],verificationJourney:'start to finish'},taskAssessment:{relevance:'unknown',reason:'insufficient evidence',remaining:'observe'}};expect(validateAnalysis(raw,input).gaps).toHaveLength(0);expect(outputSchema.required).toContain('diagnosis');raw.diagnosis.evidence[0]={...ref,sha256:digest('wrong')};expect(()=>validateAnalysis(raw,input)).toThrow();});
it('wrong-source success and agent reported fix cannot produce verified status; qualified failures remain failures',async()=>{service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'analysis'});await service.idle();let s=service.read('self');const view=s.views[0],record={schema:'project-os.scoped-observation.v1',producer:'test',sourceHash:digest('wrong'),goalHash:s.goals[0].hash,targetIds:['main'],clauseIds:['goal'],result:'passed',behaviorScope:true,invocation:{kind:'shell',argv:['test'],stdout:'ok',stderr:'',exitCode:0}},bytes=JSON.stringify(record);writeFileSync(join(evidence,'record.json'),bytes);service.observe('self',{expectedGeneration:s.generation,idempotencyKey:'record',producer:'test',rawRecord:bytes,rawHash:digest(bytes),sourceHash:record.sourceHash,goalHash:record.goalHash,targetIds:['main'],clauseIds:['goal'],result:'passed',trustedRecord:{rootIndex:0,path:'record.json'}});s=service.read('self');expect(s.observations[0].qualified).toBe(false);expect(targetStatus(view,s.observations,'main')).toBe('implemented-unverified');const failed={...record,sourceHash:view.source.hash,result:'failed',invocation:{...record.invocation,exitCode:1}},failure=JSON.stringify(failed);writeFileSync(join(evidence,'record.json'),failure);service.observe('self',{expectedGeneration:s.generation,idempotencyKey:'failure',producer:'test',rawRecord:failure,rawHash:digest(failure),sourceHash:failed.sourceHash,goalHash:failed.goalHash,targetIds:['main'],clauseIds:['goal'],result:'failed',trustedRecord:{rootIndex:0,path:'record.json'}});expect(targetStatus(view,service.read('self').observations,'main')).toBe('verified-mismatch');});
it('same failed round resumes with a new attempt; reconnect keeps one round, different goal cannot rewrite it',()=>{const a=registration();service.rounds.enroll('self',a);service.rounds.accept('self',event(a,1));service.rounds.accept('self',event(a,2,{kind:'failed',description:'turn-failed'}));const b={...a,id:'recovery',attemptId:'attempt-recovery',producerId:'producer-recovery',stream:{rootIndex:0,path:'recovery.jsonl'},beforeSnapshotId:service.rounds.capture('self').id};service.rounds.enroll('self',b);expect(projectRounds(service.read('self')).rounds).toHaveLength(1);expect(projectRounds(service.read('self')).rounds[0].attempts).toHaveLength(2);expect(()=>service.rounds.enroll('self',{...b,id:'rewrite',attemptId:'rewrite',producerId:'rewrite',purpose:'different'})).toThrow();});
it('live enrollment rejects an existing stream and explicit source exclusions are not read',async()=>{const r=registration();lines('r1',[{type:'turn.started'}]);expect(()=>service.rounds.enroll('self',r)).toThrow('历史回放');await service.close();writeFileSync(join(source,'private.json'),'secret decoy');config.projects[0].exclude=['private.json'];service=new HumanGoalService({...config,dataDir:join(root,'excluded-data')},model);expect(service.rounds.capture('self').inventory.some(x=>x.path==='private.json')).toBe(false);});
it('complete observed window prompts investigation; missing observation never becomes deviation',()=>{for(let i=1;i<=3;i++){const r=registration(`r${i}`);service.rounds.enroll('self',r);lines(`r${i}`,[{type:'turn.started'},{type:'turn.completed'}]);service.follower.follow('self',r.id);}const p=projectRounds(service.read('self'));expect(p.policy.coverageComplete).toBe(true);expect(p.policy.signal).toContain('建议调查');expect(p.rounds.every(r=>r.verified.length===0)).toBe(true);service.rounds.update('self','r2',{status:'sync-error',issue:'missing records'});expect(projectRounds(service.read('self')).policy.signal).toContain('缺观察');});
it('rollback or a newly captured checkpoint cannot reuse older passing proof as fresh round progress',async()=>{service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'old-analysis'});await service.idle();const old=service.read('self');old.views[0].createdAt='2020-01-01T00:00:00.000Z';service.store.save(old);const r=registration();service.rounds.enroll('self',r);lines('r1',[{type:'turn.started'},{type:'turn.completed'}]);service.follower.follow('self','r1');const s=service.read('self'),p=projectRounds(s).rounds[0];s.observations.push({id:'old',sourceHash:p.after!.sourceHash,goalHash:r.goalHash,producer:'test',targetIds:['main'],clauseIds:['goal'],rawRecord:'old',rawHash:digest('old'),qualified:true,qualificationReason:'test injection of older proof',invocation:null,result:'passed',createdAt:'2020-01-01T00:00:00.000Z'});service.store.save(s);expect(projectRounds(service.read('self')).rounds[0].verified).toHaveLength(0);expect(projectRounds(service.read('self')).rounds[0].viewAttemptId).toBeNull();});
it('a later terminal snapshot supersedes an earlier manual checkpoint and retains failed attempt outcome',()=>{const r=registration();service.rounds.enroll('self',r);lines('r1',[{type:'turn.started'}]);service.follower.follow('self','r1');const checkpoint=service.rounds.checkpoint('self','r1');writeFileSync(join(source,'main.ts'),'export const terminal = true;\n');appendFileSync(join(evidence,'r1.jsonl'),'{"type":"turn.failed"}\n');service.follower.follow('self','r1');const p=projectRounds(service.read('self')).rounds[0];expect(p.after!.id).not.toBe(checkpoint.id);expect(p.deltas).toHaveLength(1);expect(p.attempts[0].outcome).toBe('failed');});

async function automatic(analyzer=model,historical=false){await service.close();config.roundAnalysis={enabled:true,historical};service=new HumanGoalService(config,analyzer);}
function complete(id='r1',outcome='turn.completed'){
 const r=registration(id);service.rounds.enroll('self',r);lines(id,[{type:'turn.started'},{type:outcome}]);service.follower.follow('self',id);return r;
}
it('opt-in terminal analysis publishes once with real bound inputs; terminal polls neither read nor grow storage',async()=>{
 const analyze=vi.spyOn(model,'analyze');await automatic();complete();await service.idle();
 let s=service.read('self');expect(analyze).toHaveBeenCalledTimes(1);expect(s.attempts[0].promoted).toBe(true);expect(s.roundAnalysis?.jobs[0].state).toBe('completed');expect(s.attempts[0].input.rounds).toBeDefined();
 const follow=vi.spyOn(service.follower,'follow'),save=vi.spyOn(service.store,'save');service.follower.poll();service.follower.poll();expect(follow).not.toHaveBeenCalled();expect(save).not.toHaveBeenCalled();
 // Explicit replay still validates the immutable prefix and retains failure.
 writeFileSync(join(evidence,'r1.jsonl'),'{"type":"turn.failed "}\n{"type":"turn.completed"}\n');expect(service.follower.follow('self','r1').status).toBe('sync-error');await service.idle();expect(analyze).toHaveBeenCalledTimes(1);
});
it('default and historical policies never silently invoke a provider; explicit historical opt-in assesses captured context',async()=>{
 complete();await service.idle();expect(service.read('self').attempts).toHaveLength(0);
 await automatic();const r=registration('old','historical-replay');service.rounds.enroll('self',r);lines('old',[{type:'turn.started'},{type:'turn.completed'}]);service.follower.follow('self','old');service.rounds.checkpoint('self','old');await service.idle();expect(service.read('self').roundAnalysis?.jobs.some(j=>j.roundIds.includes(r.roundId))).toBe(false);
 await service.close();config.roundAnalysis.historical=true;service=new HumanGoalService(config,model);await service.idle();expect(service.read('self').roundAnalysis?.jobs.some(j=>j.roundIds.includes(r.roundId)&&j.state==='completed')).toBe(true);
});
it('partial terminal stream and missing dependencies never invoke automatic analysis',async()=>{
 await automatic();const r=registration();service.rounds.enroll('self',r);lines('r1',[{type:'turn.started'},{type:'turn.completed'}]);appendFileSync(join(evidence,'r1.jsonl'),'{');service.follower.follow('self','r1');await service.idle();expect(service.read('self').attempts).toHaveLength(0);
 const b=registration('pending');service.rounds.enroll('self',b);service.rounds.accept('self',event(b,1));service.rounds.accept('self',event(b,2,{kind:'cancelled',description:'cancelled',dependsOn:['absent'],sourceSnapshotId:service.rounds.capture('self').id}));service.rounds.update('self',b.id,{status:'terminal'});await service.idle();expect(service.read('self').attempts).toHaveLength(0);
});
it('bookkeeping snapshots do not invalidate exact bindings, but changed feedback does and stale model output survives',async()=>{
 let release!:(value:Analysis)=>void;const slow={...model,analyze:vi.fn((input:AnalysisInput)=>new Promise<Analysis>(resolve=>{release=async()=>resolve(await model.analyze(input));}))};
 await service.close();service=new HumanGoalService(config,slow);service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'race'});await new Promise(r=>setTimeout(r,0));service.rounds.capture('self');release(null as any);await service.idle();
 expect(service.read('self').attempts[0].promoted).toBe(true);expect(service.viewIsCurrent(service.read('self'),service.read('self').views[0])).toBe(true);
 const unchanged=service.read('self'),v=unchanged.views[0];writeFileSync(join(source,'main.ts'),'export const different=true;');service.rounds.capture('self');const changed=service.read('self');changed.rounds!.snapshots.at(-1)!.observedAt=v.source.observedAt;service.store.save(changed);expect(service.viewIsCurrent(service.read('self'),v)).toBe(false);writeFileSync(join(source,'main.ts'),'export const main = 1;\n');service.rounds.capture('self');
 service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'race2'});await new Promise(r=>setTimeout(r,0));service.feedback('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'new-goal',originalText:'new goal',kind:'desired-change',author:'human',provenance:'test',analyze:false});release(null as any);await service.idle();const s=service.read('self');expect(s.attempts[1].promoted).toBe(false);expect(s.attempts[1].result).toBeDefined();expect(s.attempts[1].error).toContain('STALE_RESULT');expect(s.goals.at(-1)?.originalText).toBe('new goal');
});
it('coalesces terminal requests while analysis runs and dispatches latest source, feedback and goal after settle',async()=>{
 let release!:()=>void,calls=0;const slow={...model,async analyze(input:AnalysisInput){calls++;if(calls===1)await new Promise<void>(r=>{release=r;});return model.analyze(input);}};await automatic(slow);
 service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'manual'});await new Promise(r=>setTimeout(r,0));complete('one');writeFileSync(join(source,'main.ts'),'export const changed=2;');complete('two');
 service.feedback('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'correct',kind:'desired-change',originalText:'latest intention',author:'human',provenance:'test',analyze:false});expect(service.read('self').roundAnalysis?.jobs.filter(j=>j.state==='pending')).toHaveLength(1);
 release();await service.idle();const s=service.read('self');expect(calls).toBe(2);expect(s.attempts[0].promoted).toBe(false);expect(s.attempts[1].promoted).toBe(true);expect(s.attempts[1].input.goal?.originalText).toBe('latest intention');expect(s.attempts[1].input.source.files[0].excerpt).toContain('changed=2');
});
it('pending survives restart, failed/cancelled provider never loops, failed development remains explicit',async()=>{
 await automatic();complete('failed-dev','turn.failed');await service.close();service=new HumanGoalService(config,{...model,async analyze(){throw new Error('provider failure retained');}});await service.idle();let s=service.read('self');expect(s.roundAnalysis?.jobs[0].state).toBe('failed');expect(projectRounds(s).rounds[0].status).toBe('failed');const n=s.attempts.length;service.follower.poll();await service.close();service=new HumanGoalService(config,model);await service.idle();expect(service.read('self').attempts).toHaveLength(n);
 let release!:()=>void;await service.close();service=new HumanGoalService(config,{...model,async analyze(input){await new Promise<void>(r=>{release=r;});return model.analyze(input);}});complete('cancel');await new Promise(r=>setTimeout(r,0));service.cancel('self',service.read('self').attempts.at(-1)!.id);release();await service.idle();s=service.read('self');expect(s.roundAnalysis?.jobs.at(-1)?.state).toBe('cancelled');service.follower.poll();await service.idle();expect(service.read('self').attempts).toHaveLength(n+1);
});
it('new evidence reanalyzes once and blocks late old-evidence publication without an extra user button',async()=>{
 await automatic();complete();await service.idle();let s=service.read('self');const view=s.views[0],raw='unqualified but retained evidence';service.observe('self',{expectedGeneration:s.generation,idempotencyKey:'evidence',producer:'test',rawRecord:raw,rawHash:digest(raw),sourceHash:view.source.hash,goalHash:s.goals[0].hash,targetIds:['main'],clauseIds:['goal'],result:'unknown'});expect(service.viewIsCurrent(service.read('self'),view)).toBe(false);await service.idle();s=service.read('self');expect(s.attempts).toHaveLength(2);expect(s.attempts[1].input.observations).toHaveLength(1);expect(s.attempts[1].promoted).toBe(true);service.reconcileRoundAnalysis('self');await service.idle();expect(service.read('self').attempts).toHaveLength(2);
});
it('analyzer-owned streams cannot recursively register as developer rounds',async()=>{
 await service.close();config.projects[0].evidenceRoots.push(config.dataDir);config.dataDir=join(root,'separate-data');
 // A new project registry is intentional; register the owning store itself below.
 config.projects[0].evidenceRoots[1]=config.dataDir;service=new HumanGoalService(config,model);
 service.feedback('self',{expectedGeneration:0,idempotencyKey:'goal',kind:'desired-change',originalText:'test',author:'human',provenance:'test',clauses:[{id:'goal',text:'actual progress',importance:'core'}],analyze:false});
 const r=registration();expect(()=>service.rounds.enroll('self',{...r,stream:{rootIndex:1,path:'output.jsonl'}})).toThrow('自己的数据目录');
});
it('successful stale automatic result rechecks changed source/goal once; current binding becomes published',async()=>{
 let release!:()=>void,calls=0;await automatic({...model,async analyze(input){calls++;if(calls===1)await new Promise<void>(r=>{release=r;});return model.analyze(input);}});complete();await new Promise(r=>setTimeout(r,0));writeFileSync(join(source,'main.ts'),'export const duringAnalysis=3;');service.feedback('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'during',kind:'desired-change',originalText:'Changed during analysis',author:'human',provenance:'test',analyze:false});release();await service.idle();const s=service.read('self');expect(calls).toBe(2);expect(s.attempts[0].promoted).toBe(false);expect(s.attempts[0].result).toBeDefined();expect(s.attempts[1].promoted).toBe(true);expect(s.attempts[1].input.source.files[0].excerpt).toContain('duringAnalysis');expect(s.views.at(-1)?.goal?.originalText).toBe('Changed during analysis');expect(service.viewIsCurrent(s,s.views.at(-1)!)).toBe(true);
});
it('explicit complete cancelled events assess failure context; source checkpoints do not call provider per item',async()=>{
 await automatic();const r=registration();service.rounds.enroll('self',r);service.rounds.accept('self',event(r,1));service.rounds.checkpoint('self',r.id);await service.idle();expect(service.read('self').attempts).toHaveLength(0);service.rounds.accept('self',event(r,2,{kind:'cancelled',description:'cancelled',sourceSnapshotId:service.rounds.capture('self').id}));await service.idle();const s=service.read('self');expect(s.attempts).toHaveLength(1);expect(projectRounds(s).rounds[0].status).toBe('cancelled');expect(s.attempts[0].promoted).toBe(true);
});
it('active no-op polls preserve immutable storage',async()=>{
 const r=registration();service.rounds.enroll('self',r);lines('r1',[{type:'turn.started'}]);service.follower.poll();const save=vi.spyOn(service.store,'save');service.follower.poll();service.follower.poll();expect(save).not.toHaveBeenCalled();
});
it('pending request cancellation survives settling another analysis and reopening',async()=>{
 let release!:()=>void;await automatic({...model,async analyze(input){await new Promise<void>(r=>{release=r;});return model.analyze(input);}});service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'holding'});await new Promise(r=>setTimeout(r,0));complete();const pending=service.read('self').roundAnalysis!.jobs[0];expect(pending.state).toBe('pending');service.cancel('self',pending.id);release();await service.idle();expect(service.read('self').attempts).toHaveLength(1);await service.close();service=new HumanGoalService(config,model);await service.idle();expect(service.read('self').attempts).toHaveLength(1);expect(service.read('self').roundAnalysis!.jobs[0].state).toBe('cancelled');
});
it('offline CLI mode durably queues without secretly starting and cancelling a provider; serve resumes',async()=>{
 await service.close();config.roundAnalysis={enabled:true,historical:false};const analyze=vi.spyOn(model,'analyze');service=new HumanGoalService(config,model,{dispatchRoundAnalysis:false});complete();await service.idle();expect(analyze).not.toHaveBeenCalled();expect(service.read('self').roundAnalysis?.jobs[0].state).toBe('pending');await service.close();service=new HumanGoalService(config,model);await service.idle();expect(analyze).toHaveBeenCalledTimes(1);expect(service.read('self').attempts[0].promoted).toBe(true);
});

it('completed shell boundaries observe live edits before terminal without a provider; repeated reads reuse inventory',async()=>{
 await automatic();const r=registration();service.rounds.enroll('self',r);lines('r1',[{type:'turn.started'}]);service.follower.follow('self','r1');
 const initial=roundData(service.read('self')).snapshots.length;
 writeFileSync(join(source,'main.ts'),'export const shellWritten = true;\n');
 const command=(id:string)=>JSON.stringify({type:'item.completed',item:{id,type:'command_execution',command:'PRIVATE command',aggregated_output:'PRIVATE output',exit_code:0}})+'\n';
 appendFileSync(join(evidence,'r1.jsonl'),command('write'));service.follower.follow('self','r1');await service.idle();
 let s=service.read('self'),p=projectRounds(s).rounds[0];expect(p.status).toBe('running');expect(p.deltas.map(f=>f.path)).toEqual(['main.ts']);expect(p.after!.inventory[0].sha256).toBe(digest('export const shellWritten = true;\n'));expect(s.attempts).toHaveLength(0);expect(s.rounds!.snapshots).toHaveLength(initial+1);
 const snapshot=p.after!.id,observation=p.lastSourceObservedAt;
 await new Promise(r=>setTimeout(r,3));appendFileSync(join(evidence,'r1.jsonl'),command('read-1')+command('read-2'));service.follower.follow('self','r1');await service.idle();s=service.read('self');p=projectRounds(s).rounds[0];expect(p.after!.id).toBe(snapshot);expect(p.lastSourceObservedAt!>observation!).toBe(true);expect(s.rounds!.snapshots).toHaveLength(initial+1);expect(s.attempts).toHaveLength(0);expect(JSON.stringify(s.rounds)).not.toContain('PRIVATE');
 appendFileSync(join(evidence,'r1.jsonl'),'\x7b"type":"turn.completed"}\n');service.follower.follow('self','r1');await service.idle();expect(service.read('self').rounds!.snapshots).toHaveLength(initial+2);expect(service.read('self').attempts).toHaveLength(1);
});
it('historical shell boundaries keep missing source observations unknown and never snapshot current source',async()=>{
 await automatic();const r=registration('old-shell','historical-replay');service.rounds.enroll('self',r);const count=service.read('self').rounds!.snapshots.length;
 writeFileSync(join(source,'main.ts'),'export const presentNotHistory=true;');lines('old-shell',[{type:'turn.started'},{type:'item.completed',item:{id:'shell',type:'command_execution',command:'unknown'}},{type:'turn.completed'}]);service.follower.follow('self',r.id);await service.idle();const s=service.read('self'),p=projectRounds(s).rounds[0];expect(p.after).toBeNull();expect(p.lastSourceObservedAt).toBeNull();expect(s.rounds!.snapshots).toHaveLength(count);expect(s.attempts).toHaveLength(0);
 // An explicitly imported historical checkpoint still has unknown capture time.
 const bytes=JSON.stringify({sourceRoot:source,trackedHashes:{'main.ts':digest('historical source')}});writeFileSync(join(evidence,'old-source.json'),bytes);const imported=service.rounds.importSnapshot('self',{rootIndex:0,path:'old-source.json',sha256:digest(bytes)});service.rounds.accept('self',event(r,4,{sourceSnapshotId:imported.id}));expect(projectRounds(service.read('self')).rounds[0].lastSourceObservedAt).toBeNull();
});
it('running projection ignores pending source events and uses the latest accepted observation, including rollback',()=>{
 const r=registration();service.rounds.enroll('self',r);const before=service.rounds.capture('self');service.rounds.accept('self',event(r,1,{sourceSnapshotId:before.id}));writeFileSync(join(source,'main.ts'),'export const changed=1;');const after=service.rounds.capture('self');service.rounds.accept('self',event(r,3,{sourceSnapshotId:after.id}));expect(projectRounds(service.read('self')).rounds[0].deltas).toHaveLength(0);service.rounds.accept('self',event(r,2));expect(projectRounds(service.read('self')).rounds[0].deltas).toHaveLength(1);writeFileSync(join(source,'main.ts'),'export const main = 1;\n');const rollback=service.rounds.capture('self',true);service.rounds.accept('self',event(r,4,{sourceSnapshotId:rollback.id}));expect(projectRounds(service.read('self')).rounds[0].after!.id).toBe(rollback.id);expect(projectRounds(service.read('self')).rounds[0].deltas).toHaveLength(0);
});
it('hash-bound readable evidence reaches rounds and model without raw execution text; legacy remains unspecified',async()=>{
 const r=complete();service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'proof-view'});await service.idle();let s=service.read('self');
 const record:any={schema:'project-os.scoped-observation.v1',producer:'test',sourceHash:s.views[0].source.hash,goalHash:r.goalHash,targetIds:['main'],clauseIds:['goal'],result:'passed',behaviorScope:true,scopeSummary:'  Checks shell checkpoint visibility\u0000  ',limitations:[' No real provider or human acceptance '],invocation:{kind:'shell',argv:['PRIVATE argv'],stdout:'PRIVATE stdout',stderr:'PRIVATE stderr',exitCode:0}};
 const observe=(key:string)=>{const bytes=JSON.stringify(record);writeFileSync(join(evidence,'scope.json'),bytes);service.observe('self',{expectedGeneration:service.read('self').generation,idempotencyKey:key,producer:record.producer,rawRecord:bytes,rawHash:digest(bytes),sourceHash:record.sourceHash,goalHash:record.goalHash,targetIds:record.targetIds,clauseIds:record.clauseIds,result:record.result,trustedRecord:{rootIndex:0,path:'scope.json'}});return bytes;};
 const raw=observe('scope-proof');s=service.read('self');expect(s.observations[0].rawRecord).toBe(raw);expect(s.observations[0].rawHash).toBe(digest(raw));expect(s.observations[0].qualified).toBe(true);expect(s.observations[0].scopeSummary).toBe('Checks shell checkpoint visibility');expect(projectRounds(s).rounds[0].verified[0].limitations).toEqual(['No real provider or human acceptance']);
 delete record.scopeSummary;delete record.limitations;observe('legacy-proof');service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'scope-analysis'});await service.idle();s=service.read('self');const input=s.attempts.at(-1)!.input;expect(input.observations[0].scopeSummary).toContain('shell checkpoint');expect(input.observations[1].scopeSummary).toBeNull();expect(input.observations[1].limitations).toBeNull();expect(JSON.stringify(input)).not.toContain('PRIVATE');
 record.scopeSummary='x'.repeat(1601);expect(()=>observe('oversized-summary')).toThrow();expect(service.read('self').observations).toHaveLength(2);
 record.scopeSummary='scope cannot qualify a wrong source';record.sourceHash=digest('wrong');observe('wrong-source-readable');expect(service.read('self').observations.at(-1)!.qualified).toBe(false);
});

it('source windows supply exact contiguous lines, mark every gap and reject references crossing unseen bytes',async()=>{
 const raw=Array.from({length:180},(_,i)=>i%12===0?`export function f${i}() {`:`  // line ${i+1} ${'x'.repeat(45)}`).join('\n');writeFileSync(join(source,'main.ts'),raw);
 const snapshot=discoverSource(service.project('self'),{perFileBytes:1800,maxBytes:2000}),f=snapshot.files[0];expect(f.sha256).toBe(digest(raw));expect(f.truncated).toBe(true);expect(f.excerpt).toContain('OMITTED');expect(f.excerpt).toContain('SOURCE WINDOW');expect(snapshot.suppliedBytes).toBe(Buffer.byteLength(f.excerpt));expect(snapshot.suppliedBytes).toBeLessThanOrEqual(1800);
 const supplied=f.excerpt.split('\n').filter(l=>/^\d+: /.test(l));expect(supplied).toHaveLength(f.suppliedLines);for(const range of f.ranges)for(let line=range.start;line<=range.end;line++)expect(supplied).toContain(`${line}: ${raw.split('\n')[line-1]}`);
 service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'window-input'});await service.idle();const input=structuredClone(service.read('self').attempts[0].input);input.source=snapshot;const output=await model.analyze(input),range=f.ranges[0];output.purposeRefs=[{path:f.path,sha256:f.sha256,start:range.start,end:range.end}];expect(()=>validateAnalysis(output,input)).not.toThrow();output.purposeRefs[0].end=f.ranges[1].start;expect(()=>validateAnalysis(output,input)).toThrow('未提供');expect(makePrompt(input)).toContain('禁止跨窗口补全');expect(makePrompt(input)).toContain('null 表示未说明');
});
it('whole small sources stay contiguous and default file allocation preserves the total source ceiling',()=>{
 writeFileSync(join(source,'main.ts'),'export function small() {\n  return 1;\n}');const small=discoverSource(service.project('self'));expect(small.files[0].ranges).toEqual([{start:1,end:3}]);expect(small.files[0].truncated).toBe(false);
 for(let i=0;i<30;i++)writeFileSync(join(source,`large-${i}.ts`),Array.from({length:300},(_,j)=>`export const value${j} = "${'a'.repeat(70)}";`).join('\n'));const many=discoverSource(service.project('self'));expect(many.files).toHaveLength(31);expect(many.suppliedBytes).toBeLessThanOrEqual(350000);expect(many.files.every(f=>Buffer.byteLength(f.excerpt)<=16000)).toBe(true);
});

const largeCommand=(bytes=545232,id='large')=>{const x={type:'item.completed',item:{id,type:'command_execution',command:'PRIVATE argv',aggregated_output:'',status:'completed',exit_code:0}};x.item.aggregated_output='X'.repeat(bytes-Buffer.byteLength(JSON.stringify(x)));return JSON.stringify(x);};
async function optInLargeEvents(){await service.close();config.eventReadPolicy={maxRecordBytes:1048576};service=new HumanGoalService(config,model);}
it('record policy is opt-in, bounded and validated before opening a store',()=>{
 expect(service.config.eventReadPolicy).toEqual({maxRecordBytes:256000});
 for(const value of [1048577,0,-1,256000.5,'1048576',null])expect(()=>new HumanGoalService({...config,eventReadPolicy:{maxRecordBytes:value}},model)).toThrow();
 expect(()=>new HumanGoalService({...config,eventReadPolicy:{maxRecordBytes:1048576,unlimited:true}},model)).toThrow();
});
it('explicit same-stream recovery retains default failure, exact cursor and history across restart without leaking command text',async()=>{
 const r=registration();service.rounds.enroll('self',r);writeFileSync(join(evidence,'r1.jsonl'),JSON.stringify({type:'turn.started'})+'\n'+largeCommand()+'\n'+JSON.stringify({type:'turn.completed'})+'\n');
 const failed=service.follower.follow('self','r1');expect(failed.issue).toContain('STREAM_RECORD_LIMIT');expect(failed.line).toBe(1);expect(failed.syncHistory?.[0].maxRecordBytes).toBe(256000);
 const original=structuredClone(roundData(service.read('self')).snapshots),oldEvent=structuredClone(roundData(service.read('self')).events[0]);
 await optInLargeEvents();service.follower.poll();expect(roundData(service.read('self')).registrations[0].offset).toBe(failed.offset);
 writeFileSync(join(source,'main.ts'),'export const laterRoundChange = true;\n');const at=new Date().toISOString();const recovered=service.follower.follow('self','r1');expect(recovered.status).toBe('terminal');expect(recovered.issue).toBeNull();expect(recovered.line).toBe(3);expect(recovered.cursor).toBe(3);expect(recovered.syncHistory?.map(e=>e.kind)).toEqual(['error','replay','recovered']);expect(recovered.syncHistory?.[1].offset).toBe(failed.offset);expect(recovered.syncHistory?.[1].prefixHash).toBe(failed.prefixHash);expect(recovered.syncHistory?.[2].maxRecordBytes).toBe(1048576);
 const d=roundData(service.read('self'));expect(d.snapshots.slice(0,original.length)).toEqual(original);expect(d.events[0]).toEqual(oldEvent);expect(d.events.slice(1).every(e=>e.event.sourceTiming==='recovery-read-time'&&e.event.observedAt>=at)).toBe(true);expect(JSON.stringify(projectRounds(service.read('self')))).not.toContain('PRIVATE');expect(projectRounds(service.read('self')).rounds[0].delayedRecovery).toBe(true);
 const count=d.snapshots.length;service.follower.follow('self','r1');await service.close();service=new HumanGoalService(config,model);service.follower.follow('self','r1');expect(roundData(service.read('self')).events).toHaveLength(3);expect(roundData(service.read('self')).snapshots).toHaveLength(count);expect(roundData(service.read('self')).registrations[0].syncHistory).toEqual(recovered.syncHistory);
});
it('legacy sync-error is retained on explicit replay and its unrecorded policy stays unknown',async()=>{
 const r=registration();service.rounds.enroll('self',r);lines('r1',[{type:'turn.started'},{type:'turn.completed'}]);service.rounds.update('self','r1',{status:'sync-error',issue:'STREAM_RECORD_LIMIT: legacy',lastCheckedAt:'2026-09-17T00:00:00.000Z'});await optInLargeEvents();const recovered=service.follower.follow('self','r1');expect(recovered.syncHistory?.[0]).toMatchObject({kind:'error',issue:'STREAM_RECORD_LIMIT: legacy',at:'2026-09-17T00:00:00.000Z',maxRecordBytes:null});expect(recovered.delayedRecovery).toBe(true);
});
it('1MiB accepts the exact byte bound and rejects above-bound, invalid JSON and unsupported envelopes',async()=>{
 await optInLargeEvents();for(const [id,raw,issue] of [['exact',largeCommand(1048576),null],['over',largeCommand(1048577),'STREAM_RECORD_LIMIT'],['json','{"type":'+ ' '.repeat(545232),'STREAM_SCHEMA'],['schema',JSON.stringify({type:'item.completed',item:{id:'x',type:'unsupported',output:'X'.repeat(545232)}}),'STREAM_SCHEMA']] as const){const r=registration(id);service.rounds.enroll('self',r);writeFileSync(join(evidence,`${id}.jsonl`),raw+'\n');const result=service.follower.follow('self',id);if(issue){expect(result.issue).toContain(issue);expect(result.offset).toBe(0);}else{expect(result.issue).toBeNull();expect(result.line).toBe(1);}}
});
it('large partial records wait intact and batches never exceed 2MB or invent terminal events',async()=>{
 await optInLargeEvents();const r=registration();service.rounds.enroll('self',r);const raw=largeCommand(1048576);writeFileSync(join(evidence,'r1.jsonl'),raw.slice(0,600000));expect(service.follower.follow('self','r1').status).toBe('partial-line');expect(roundData(service.read('self')).events).toHaveLength(0);appendFileSync(join(evidence,'r1.jsonl'),raw.slice(600000)+'\n');expect(service.follower.follow('self','r1').line).toBe(1);
 const b=registration('batch');service.rounds.enroll('self',b);writeFileSync(join(evidence,'batch.jsonl'),'{"type":"turn.started"}\n'+[0,1,2,3].map(i=>largeCommand(700000,`b${i}`)+'\n').join('')+'{"type":"turn.completed"}\n');const first=service.follower.follow('self','batch');expect(first.status).toBe('following');expect(first.offset).toBeLessThanOrEqual(2000000);expect(first.line).toBe(3);const second=service.follower.follow('self','batch');expect(second.status).toBe('terminal');expect(second.line).toBe(6);expect(roundData(service.read('self')).events.filter(e=>e.event.registrationId==='batch')).toHaveLength(6);
});
it('recovery across batches survives restart and cannot bypass consumed-prefix tampering',async()=>{
 const r=registration();service.rounds.enroll('self',r);writeFileSync(join(evidence,'r1.jsonl'),'{"type":"turn.started"}\n'+[0,1,2,3].map(i=>largeCommand(700000,`b${i}`)+'\n').join('')+'{"type":"turn.completed"}\n');expect(service.follower.follow('self','r1').issue).toContain('STREAM_RECORD_LIMIT');await optInLargeEvents();const first=service.follower.follow('self','r1');expect(first.status).toBe('following');expect(first.recoveryThroughOffset).toBeGreaterThan(first.offset);expect(first.syncHistory?.map(e=>e.kind)).toEqual(['error','replay']);await service.close();service=new HumanGoalService(config,model);service.follower.poll();const recovered=roundData(service.read('self')).registrations[0];expect(recovered.status).toBe('terminal');expect(recovered.syncHistory?.map(e=>e.kind)).toEqual(['error','replay','recovered']);const raw=readFileSync(join(evidence,'r1.jsonl'),'utf8');writeFileSync(join(evidence,'r1.jsonl'),raw.replace('turn.started','turn.changed'));expect(service.follower.follow('self','r1').issue).toContain('STREAM_CHANGED');expect(roundData(service.read('self')).events).toHaveLength(6);
});
it('later round-scoped proof cannot solve a delayed old round sharing its read-time hash; unscoped legacy stays global',async()=>{
 const old=registration('old');service.rounds.enroll('self',old);writeFileSync(join(evidence,'old.jsonl'),'{"type":"turn.started"}\n'+largeCommand()+'\n{"type":"turn.completed"}\n');service.follower.follow('self','old');
 const preRepair=service.rounds.checkpoint('self','old');const current=registration('current');service.rounds.enroll('self',current);writeFileSync(join(source,'main.ts'),'export const repair = true;\n');await optInLargeEvents();service.follower.follow('self','old');lines('current',[{type:'turn.started'},{type:'turn.completed'}]);service.follower.follow('self','current');service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'proof-view'});await service.idle();
 const s=service.read('self'),projection=projectRounds(s);expect(projection.rounds[0].after!.sourceHash).toBe(projection.rounds[1].after!.sourceHash);expect(s.rounds!.snapshots.find(x=>x.id===preRepair.id)).toEqual(preRepair);
 const record:any={schema:'project-os.scoped-observation.v1',producer:'test',sourceHash:s.views[0].source.hash,goalHash:old.goalHash,targetIds:['main'],clauseIds:['goal'],roundIds:[current.roundId],result:'passed',behaviorScope:true,invocation:{kind:'shell',argv:['PRIVATE'],stdout:'PRIVATE',stderr:'',exitCode:0}};
 const observe=(key:string)=>{const bytes=JSON.stringify(record);writeFileSync(join(evidence,'proof.json'),bytes);return service.observe('self',{expectedGeneration:service.read('self').generation,idempotencyKey:key,producer:'test',rawRecord:bytes,rawHash:digest(bytes),sourceHash:record.sourceHash,goalHash:record.goalHash,targetIds:record.targetIds,clauseIds:record.clauseIds,result:record.result,trustedRecord:{rootIndex:0,path:'proof.json'}});};
 observe('current-proof');expect(projectRounds(service.read('self')).rounds.map(r=>r.verified.length)).toEqual([0,1]);expect(service.read('self').observations[0].roundIds).toEqual([current.roundId]);record.roundIds=['missing-round'];expect(()=>observe('invalid-round')).toThrow();record.roundIds=[];expect(()=>observe('empty-round')).toThrow();record.roundIds=[current.roundId,current.roundId];expect(()=>observe('duplicate-round')).toThrow();delete record.roundIds;observe('legacy-proof');expect(projectRounds(service.read('self')).rounds.map(r=>r.verified.length)).toEqual([0,2]);expect(targetStatus(s.views[0],service.read('self').observations,'main')).toBe('verified-aligned');
 service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'scoped-input'});await service.idle();const input=service.read('self').attempts.at(-1)!.input;expect(input.observations[0].roundIds).toEqual([current.roundId]);expect(JSON.stringify(input.rounds)).toContain('recovery-read-time');expect(JSON.stringify(input)).not.toContain('PRIVATE');
});
it('missing stream during explicit recovery stays stopped until another explicit replay',async()=>{
 const r=registration();service.rounds.enroll('self',r);writeFileSync(join(evidence,'r1.jsonl'),largeCommand()+'\n');service.follower.follow('self','r1');renameSync(join(evidence,'r1.jsonl'),join(evidence,'held.jsonl'));await optInLargeEvents();expect(service.follower.follow('self','r1').status).toBe('sync-error');renameSync(join(evidence,'held.jsonl'),join(evidence,'r1.jsonl'));service.follower.poll();expect(roundData(service.read('self')).events).toHaveLength(0);expect(service.follower.follow('self','r1').line).toBe(1);
});


async function legacyRoundProof(behaviorScope=true){
 const r=registration();service.rounds.enroll('self',r);
 service.analyze('self',{expectedGeneration:service.read('self').generation,idempotencyKey:'legacy-proof-analysis'});await service.idle();
 const s=service.read('self'),record={schema:'project-os.scoped-observation.v1',producer:'synthetic-shell',sourceHash:s.views[0].source.hash,goalHash:s.goals[0].hash,targetIds:['main'],clauseIds:['goal'],roundIds:[r.roundId],scopeSummary:'Synthetic scoped proof',limitations:['No real provider'],result:'passed' as const,behaviorScope,invocation:{kind:'shell',argv:['synthetic-check'],stdout:'passed',stderr:'',exitCode:0}},rawRecord=JSON.stringify(record),rawHash=digest(rawRecord),ref={rootIndex:0,path:'legacy.json',sha256:rawHash};
 writeFileSync(join(evidence,ref.path),rawRecord);
 const request={expectedGeneration:s.generation,idempotencyKey:`round-evidence-${rawHash.slice(0,40)}`,producer:record.producer,rawRecord,rawHash,sourceHash:record.sourceHash,goalHash:record.goalHash,targetIds:record.targetIds,clauseIds:record.clauseIds,result:record.result,trustedRecord:{rootIndex:ref.rootIndex,path:ref.path}};
 // Persist through the unchanged pre-round-6 observe protocol, not the new importer.
 const receipt=service.observe('self',request);
 expect(service.read('self').idempotency[request.idempotencyKey]).toEqual({payloadHash:hash(request),result:receipt});
 return {ref,request,receipt,record};
}
it.each([true,false])('legacy successful import replay preserves saved qualification=%s, original bytes and historical scope after reopen',async(qualified)=>{
 const {ref,request,receipt}=await legacyRoundProof(qualified),legacy=service.read('self'),object=join(config.dataDir,'sessions','self',`${hash(legacy)}.json`),bytes=readFileSync(object,'utf8');
 expect(legacy.observations[0].qualified).toBe(qualified);
 service.feedback('self',{expectedGeneration:legacy.generation,idempotencyKey:'after-proof',originalText:'New current goal',kind:'desired-change',author:'test',provenance:'test',analyze:false});
 writeFileSync(join(source,'main.ts'),'export const changed=2;');service.rounds.capture('self');
 await service.close();service=new HumanGoalService(config,model);const before=service.read('self'),pointer=join(config.dataDir,'sessions','self','current.json'),pointerBytes=readFileSync(pointer,'utf8'),projection=projectRounds(before);
 const save=vi.spyOn(service.store,'save');expect(service.importRoundEvidence('self',ref)).toEqual(receipt);expect(save).not.toHaveBeenCalled();
 expect(service.read('self')).toEqual(before);expect(projectRounds(service.read('self'))).toEqual(projection);expect(readFileSync(pointer,'utf8')).toBe(pointerBytes);expect(readFileSync(object,'utf8')).toBe(bytes);
 expect(service.read('self').idempotency[request.idempotencyKey]).toEqual(legacy.idempotency[request.idempotencyKey]);expect(service.read('self').observations).toEqual(legacy.observations);
});
it('same evidence key still conflicts on content, trusted root/path, producer, source, goal, targets, clauses and round scope',async()=>{
 const {ref,request,record}=await legacyRoundProof();const before=service.read('self');
 for(const changed of [{producer:'other'},{sourceHash:digest('other')},{goalHash:digest('other')},{targetIds:['other']},{clauseIds:['other']},{result:'failed'},{rawHash:digest('other')},{rawRecord:request.rawRecord+' '},{trustedRecord:{rootIndex:1,path:ref.path}},{trustedRecord:{rootIndex:0,path:'copy.json'}},{rawRecord:JSON.stringify({...record,roundIds:['other-round']})}]){
  expect(()=>service.observe('self',{...request,...changed})).toThrow(expect.objectContaining({code:'IDEMPOTENCY_CONFLICT'}));
 }
 writeFileSync(join(evidence,'copy.json'),request.rawRecord);
 for(const path of ['copy.json','./legacy.json'])expect(()=>service.importRoundEvidence('self',{...ref,path})).toThrow(expect.objectContaining({code:'IDEMPOTENCY_CONFLICT'}));
 expect(service.read('self')).toEqual(before);
});
it('repeat import revalidates trusted bytes and paths while a fresh observation retains stale CAS and raw hash checks',async()=>{
 const {ref,request}=await legacyRoundProof(),before=service.read('self');
 writeFileSync(join(evidence,ref.path),request.rawRecord+' ');expect(()=>service.importRoundEvidence('self',ref)).toThrow(expect.objectContaining({code:'EVIDENCE_HASH'}));
 writeFileSync(join(evidence,ref.path),request.rawRecord);expect(()=>service.importRoundEvidence('self',{...ref,rootIndex:99})).toThrow();expect(()=>service.importRoundEvidence('self',{...ref,path:'../source/main.ts'})).toThrow();
 rmSync(join(evidence,ref.path));symlinkSync(join(source,'main.ts'),join(evidence,ref.path));expect(()=>service.importRoundEvidence('self',ref)).toThrow();rmSync(join(evidence,ref.path));writeFileSync(join(evidence,ref.path),request.rawRecord);
 expect(service.read('self')).toEqual(before);
 expect(()=>service.observe('self',{...request,idempotencyKey:'fresh-stale'})).toThrow(expect.objectContaining({code:'STALE_BASE'}));
 const stale=service.read('self');expect(stale.generation).toBe(before.generation);expect(stale.observations).toEqual(before.observations);expect(stale.conflicts.at(-1)?.reason).toBe('STALE_BASE');expect(stale.idempotency['fresh-stale']).toBeUndefined();
 expect(()=>service.observe('self',{...request,idempotencyKey:'fresh-tamper',expectedGeneration:stale.generation,rawHash:digest('tampered')})).toThrow(expect.objectContaining({code:'EVIDENCE_UNQUALIFIED'}));
 expect(service.read('self')).toEqual(stale);expect(service.importRoundEvidence('self',ref)).toEqual(before.idempotency[request.idempotencyKey].result);expect(service.read('self')).toEqual(stale);
});

it('idle missing producers do not reread history; file appearance still follows the real turn',()=>{
 const r=registration('idle-missing','historical-replay');service.rounds.enroll('self',r);service.follower.poll();
 expect(roundData(service.read('self')).registrations[0].issue).toContain('STREAM_MISSING');
 const load=vi.spyOn(service.store,'load');service.follower.poll();load.mockClear();const pointer=readFileSync(join(config.dataDir,'sessions/self/current.json'),'utf8');
 service.follower.poll();service.follower.poll();expect(load).not.toHaveBeenCalled();expect(readFileSync(join(config.dataDir,'sessions/self/current.json'),'utf8')).toBe(pointer);
 lines('idle-missing',[{type:'turn.started'},{type:'turn.completed'}]);service.follower.poll();
 expect(roundData(service.read('self')).registrations[0].status).toBe('terminal');expect(roundData(service.read('self')).events).toHaveLength(2);
});
it('idle observation index notices durable changes even when generation stays the same',()=>{
 const r=registration('idle-change','historical-replay');service.rounds.enroll('self',r);service.follower.poll();service.follower.poll();const generation=service.read('self').generation;
 service.rounds.update('self','idle-change',{status:'unsupported',issue:'explicit stop in fixture'});expect(service.read('self').generation).toBe(generation);
 const load=vi.spyOn(service.store,'load');service.follower.poll();expect(load).toHaveBeenCalledTimes(1);load.mockClear();service.follower.poll();expect(load).not.toHaveBeenCalled();
});
it('idle observation never hides corrupted immutable state behind an unchanged pointer',()=>{
 const r=registration('idle-corrupt','historical-replay');service.rounds.enroll('self',r);service.follower.poll();service.follower.poll();
 const dir=join(config.dataDir,'sessions/self'),ref=JSON.parse(readFileSync(join(dir,'current.json'),'utf8')),state=service.read('self');state.projectId='other';writeFileSync(join(dir,ref.hash+'.json'),JSON.stringify(state));
 expect(()=>service.follower.poll()).toThrow('状态损坏');
});
