import { afterEach, expect, it } from 'vitest';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { HumanGoalService } from '../../src/core/human-goal-workflow/service.js';
import { hash, type AnalysisInput, type Analysis, type Scenario, type Analyzer } from '../../src/core/human-goal-workflow/types.js';
import { activeConfirmation, projectClosedLoop } from '../../src/core/human-goal-workflow/scenarios.js';
import { runVerification, verificationContext } from '../../src/core/human-goal-workflow/verification.js';
const roots:string[]=[],services:HumanGoalService[]=[];
afterEach(async()=>{for(const s of services.splice(0))await s.close();for(const r of roots.splice(0))rmSync(r,{recursive:true,force:true});});
export const scenario:Scenario={id:'scenario-read',title:'Read result',critical:'critical',given:'A saved goal',when:'Read current state',then:'The goal is retained',clauseIds:['c1'],journeyIds:[],targetIds:['reader'],mapping:'unknown',uncertainty:'Journey not mapped',criteria:[{id:'retained',text:'Goal survives reopen',observable:'Read goal text after reopening',clauseIds:['c1'],journeyIds:[],targetIds:['reader'],mapping:'unknown',uncertainty:'Journey not mapped'}]};
function model(i:AnalysisInput):Analysis {const f=i.source.files[0],ref={path:f.path,sha256:f.sha256,start:1,end:1};return {scenarios:[structuredClone(scenario)],purpose:'Read state',purposeRefs:[ref],limitations:[],modules:[{id:'reader',title:'Reader',kind:'discovered',responsibility:'read',inputs:[],outputs:[],refs:[ref],supersedes:[]}],edges:[],alignments:[],gaps:[],conflicts:[],changes:[],coverageNotes:'fixture',feedbackResponse:'fixture'};}
async function fixture(analyzer?:Analyzer){const root=mkdtempSync(join(tmpdir(),'closed-loop-'));roots.push(root);const source=join(root,'source');mkdirSync(source);mkdirSync(join(root,'evidence'));writeFileSync(join(source,'main.ts'),'export const read = () => 1;\n');const config={projects:[{id:'self',label:'self',sourceRoot:source,scope:['main.ts'],revision:'fixture',sourceKind:'working-tree',subjectId:'self',caseRole:'self-case',evidenceRoots:[join(root,'evidence')]}],dataDir:join(root,'data'),analyzer:{timeoutMs:null}};const s=new HumanGoalService(config,analyzer??{revision:'fixture',async analyze(i){return model(i);}});services.push(s);s.feedback('self',{expectedGeneration:0,idempotencyKey:'goal',originalText:'Retain goal',kind:'desired-change',author:'test',provenance:'fixture',clauses:[{id:'c1',text:'Retain goal',importance:'core'}],analyze:true});await s.idle();return {s,root,source,config};}
function confirm(s:HumanGoalService){const state=s.read('self'),proposal=state.scenarioSets!.at(-1)!;return s.reviewScenarios('self',{expectedGeneration:state.generation,idempotencyKey:'confirm',proposalId:proposal.id,decision:'confirm',author:'owner',roundId:null,scenarios:[{...scenario,title:'Edited by owner'}],analyze:false});}
it('model proposes; one edited confirmation is durable and replayed without a second write',async()=>{const {s}=await fixture();expect(activeConfirmation(s.read('self'))).toBeNull();const before=s.read('self');const request={expectedGeneration:before.generation,idempotencyKey:'confirm',proposalId:before.scenarioSets!.at(-1)!.id,decision:'confirm',author:'owner',roundId:null,scenarios:[{...scenario,title:'Edited once'}],analyze:false};const result=s.reviewScenarios('self',request);expect(s.reviewScenarios('self',request)).toEqual(result);expect(activeConfirmation(s.store.load('self')!)!.scenarios[0].title).toBe('Edited once');expect(s.read('self').scenarioSets).toHaveLength(2);expect(()=>s.reviewScenarios('self',{...request,author:'other'})).toThrow();});
it('goal change retires authoritative module expectations and confirmation without erasing history',async()=>{const {s}=await fixture();confirm(s);const state=s.read('self');state.expectations=[{targetId:'reader',responsibility:'old expectation',inputs:[],outputs:[],examples:[],clauseIds:['c1'],disposition:'required',replaces:[]}];s.store.save(state);s.feedback('self',{expectedGeneration:state.generation,idempotencyKey:'new-goal',originalText:'New goal',kind:'desired-change',author:'owner',provenance:'test',analyze:false});const after=s.read('self');expect(activeConfirmation(after)).toBeNull();expect(after.expectations).toEqual([]);expect(after.expectationHistory![0].expectations[0].responsibility).toBe('old expectation');expect(after.scenarioSets).toHaveLength(2);expect(projectClosedLoop(after,after.views[0].source.hash).status).not.toBe('verified');});
it('a goal change while the model is pending cannot publish old proposals',async()=>{let release!:(v:unknown)=>void;let started!:(v?:unknown)=>void;const ready=new Promise(r=>started=r);const pending:Analyzer={revision:'pending',analyze:async i=>{started();return new Promise(r=>release=()=>r(model(i)));}};const setup=fixture(pending);await ready;const s=services.at(-1)!;s.feedback('self',{expectedGeneration:s.read('self').generation,idempotencyKey:'change',originalText:'Changed',kind:'desired-change',author:'owner',provenance:'test',analyze:false});release(null);await setup;expect(s.read('self').scenarioSets??[]).toEqual([]);expect(s.read('self').attempts[0].error).toContain('STALE_RESULT');});
it('unmapped criteria, no receipt and agent reports cannot make the whole loop green',async()=>{const {s}=await fixture();confirm(s);const projection=projectClosedLoop(s.read('self'),s.read('self').views[0].source.hash);expect(projection.status).not.toBe('verified');expect(projection.criteria[0].status).toBe('unknown');});
import { digest } from '../../src/core/human-goal-workflow/types.js';
import { discoverSource } from '../../src/core/human-goal-workflow/source.js';
import { validateReceipt } from '../../src/core/human-goal-workflow/verification.js';
import { validateScenarios } from '../../src/core/human-goal-workflow/scenarios.js';
function enroll(s:HumanGoalService,source:string){const before=s.rounds.capture('self');s.rounds.enroll('self',{id:'registration',projectId:'self',repoRoot:source,worktreeRoot:source,branch:'fixture',tool:'codex-exec',toolVersion:'0.155.0-alpha.2.6',taskId:'task',roundId:'round',attemptId:'attempt',producerId:'producer',mode:'live',goalHash:s.read('self').goals.at(-1)!.hash,feedbackIds:[],purpose:'Check retained goal',clauseIds:['c1'],journeyIds:[],selectedActionIds:[],acceptedPlan:null,beforeSnapshotId:before.id,stream:{rootIndex:0,path:'stream.jsonl'},deferredBenefit:null});}
function registerCheck(s:HumanGoalService,code:string,prerequisites:{kind:'path'|'env';value:string}[]=[]){s.config.verificationChecks.self=[{id:'check',label:'Fixture observable check',argv:[process.execPath,'-e',code],prerequisites,bindings:[{assertionId:'retained',scenarioId:scenario.id,criterionId:'retained'}]}];}
function assertion(status:string){return `console.log('PROJECT_OS_ASSERTION '+JSON.stringify({assertionId:'retained',status:${JSON.stringify(status)},actual:'Observed fixture condition',evidence:'Explicit fixture assertion'}));`;}
it.each(['passed','behavior-failed','missing-capability','unknown'])('structured execution records %s independently of generic command outcome',async status=>{const {s,source}=await fixture();confirm(s);enroll(s,source);registerCheck(s,assertion(status)+(status==='passed'?'':'process.exitCode=1;'));const context=verificationContext(s.read('self'),s.project('self'),'round');const r=await runVerification(s.config,s.project('self'),context,['check']);expect(r.checks[0].assertions[0].status).toBe(status);expect(validateReceipt(r,s.read('self'),s.project('self'),s.config)).toEqual(r);});
it('exit zero without an assertion and generic nonzero are unknown, not feature missing or success',async()=>{const {s,source}=await fixture();confirm(s);enroll(s,source);for(const code of ['console.log("unrelated tests passed")','process.exitCode=1',assertion('passed')+'process.exitCode=1',assertion('passed')+assertion('passed')]){registerCheck(s,code);const r=await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['check']);expect(r.checks[0].assertions[0].status).toBe('unknown');}});
it('environment preflight blocks execution separately and receipt tampering is rejected',async()=>{const {s,source}=await fixture();confirm(s);enroll(s,source);registerCheck(s,assertion('passed'),[{kind:'path',value:'not-configured'}]);const r=await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['check']);expect(r.checks[0].exitCode).toBeNull();expect(r.checks[0].stdout).toBe('');expect(r.checks[0].assertions[0].status).toBe('environment-blocked');expect(validateReceipt(r,s.read('self'),s.project('self'),s.config)).toEqual(r);r.checks[0].assertions[0].status='passed';const {hash:_,...base}=r;r.hash=hash(base);expect(()=>validateReceipt(r,s.read('self'),s.project('self'),s.config)).toThrow('条件结果');});
it('source changes during execution invalidate otherwise passing proof; old receipt is retained',async()=>{const {s,source,root}=await fixture();confirm(s);enroll(s,source);registerCheck(s,"require('fs').appendFileSync('main.ts','// changed\n');".replace('// changed\n','// changed\\n')+assertion('passed'));const r=await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['check']);expect(r.sourceChanged).toBe(true);const bytes=JSON.stringify(r);writeFileSync(join(root,'evidence','receipt.json'),bytes);s.importVerification('self',{expectedGeneration:s.read('self').generation,idempotencyKey:'import',record:{rootIndex:0,path:'receipt.json',sha256:digest(bytes)}});expect(s.read('self').verificationReceipts).toHaveLength(1);expect(s.closedLoop('self').criteria[0].status).toBe('unknown');expect(s.closedLoop('self').receipts[0].current).toBe(false);});
it('receipt replay survives reopen and only current confirmed conditions receive evidence',async()=>{const {s,source,root,config}=await fixture();confirm(s);enroll(s,source);registerCheck(s,assertion('passed'));const r=await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['check']),bytes=JSON.stringify(r);writeFileSync(join(root,'evidence','proof.json'),bytes);const request={expectedGeneration:s.read('self').generation,idempotencyKey:'proof',record:{rootIndex:0,path:'proof.json',sha256:digest(bytes)}};const result=s.importVerification('self',request);expect(s.importVerification('self',request)).toEqual(result);expect(s.closedLoop('self').criteria[0].status).toBe('passed');const configured=s.config;await s.close();services.splice(services.indexOf(s),1);const reopened=new HumanGoalService({...config,verificationChecks:configured.verificationChecks},{revision:'fixture',async analyze(i){return model(i);}});services.push(reopened);expect(reopened.importVerification('self',request)).toEqual(result);expect(reopened.read('self').verificationReceipts).toHaveLength(1);writeFileSync(join(source,'main.ts'),'export const read = () => 2;');expect(reopened.closedLoop('self').criteria[0].status).toBe('unknown');});
it('validates many-to-many mappings and distinguishes shared blockers without inferring architecture failure',async()=>{const {s}=await fixture();confirm(s);const state=s.read('self'),set=activeConfirmation(state)!;set.scenarios.push({...structuredClone(scenario),id:'second',criteria:[{...scenario.criteria[0],id:'second-criterion'}]});const p=projectClosedLoop(state,state.views[0].source.hash);expect(p.commonBlockers).toEqual([{targetId:'reader',scenarioIds:['scenario-read','second']}]);expect(p.priorityReason).toContain('不证明架构失败');expect(()=>validateScenarios([{...scenario,mapping:'mapped'}],state.views[0].analysis,state.goals[0])).toThrow('unknown');expect(()=>validateScenarios([{...scenario,targetIds:['not-real']}],state.views[0].analysis,state.goals[0])).toThrow();});
it('a rejected proposal is retained and revokes confirmation without running code',async()=>{const {s}=await fixture();confirm(s);const state=s.read('self');s.reviewScenarios('self',{expectedGeneration:state.generation,idempotencyKey:'reject',proposalId:state.scenarioSets![0].id,decision:'reject',author:'owner',roundId:null,scenarios:[scenario],analyze:false});expect(activeConfirmation(s.read('self'))).toBeNull();expect(s.read('self').scenarioSets).toHaveLength(3);});
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { readFileSync } from 'node:fs';
it('local CLI executes only selected registered argv and writes a replayable immutable receipt',async()=>{const {s,source,root}=await fixture();confirm(s);enroll(s,source);registerCheck(s,assertion('passed'));const path=join(root,'config.json'),out=join(root,'evidence','cli.json');writeFileSync(path,JSON.stringify(s.config));await s.close();services.splice(services.indexOf(s),1);const argv=['--import','tsx','scripts/project-os-verify.ts','--config',path,'--project','self','--round','round','--checks','check','--output',out];const result=await promisify(execFile)(process.execPath,argv);expect(JSON.parse(result.stdout).conditions[0].status).toBe('passed');const bytes=readFileSync(out);await expect(promisify(execFile)(process.execPath,argv)).rejects.toThrow();expect(readFileSync(out)).toEqual(bytes);});
it('a source edit reverted within a check still invalidates proof through file metadata',async()=>{const {s,source}=await fixture();confirm(s);enroll(s,source);registerCheck(s,"const f=require('fs');const b=f.readFileSync('main.ts');f.writeFileSync('main.ts','temporary');f.writeFileSync('main.ts',b);"+assertion('passed'));const r=await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['check']);expect(r.sourceAfterHash).toBe(r.binding.sourceHash);expect(r.sourceChanged).toBe(true);});
it('runtime calls require explicit trace events bound to existing endpoints, never static imports',async()=>{const {s,source}=await fixture();confirm(s);enroll(s,source);const state=s.read('self'),view=state.views[state.currentView!];view.analysis.edges.push({id:'call',from:'reader',to:'reader',label:'call candidate',expected:'call',actual:'static only',kind:'call',certainty:'source-supported',refs:view.analysis.modules[0].refs});s.store.save(state);expect(s.closedLoop('self').runtimeCalls).toEqual([]);registerCheck(s,assertion('passed')+"console.log('PROJECT_OS_TRACE '+JSON.stringify({id:'trace-event',from:'reader',to:'reader',edgeId:'call',traceId:'actual-fixture-trace',event:'enter',evidence:'Instrumented fixture function entry'}));");const receipt=await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['check']);expect(receipt.checks[0].traces).toHaveLength(1);expect(validateReceipt(receipt,s.read('self'),s.project('self'),s.config)).toEqual(receipt);registerCheck(s,"console.log('PROJECT_OS_TRACE '+JSON.stringify({id:'bad',from:'absent',to:'reader',edgeId:'call',traceId:'invalid',event:'enter',evidence:'invalid endpoints'}));");const invalid=await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['check']);expect(invalid.checks[0].traces).toEqual([]);expect(invalid.checks[0].assertions[0].status).toBe('unknown');});
it('a missing executable is an explicit environment preflight result, not missing capability',async()=>{const {s,source}=await fixture();confirm(s);enroll(s,source);registerCheck(s,assertion('passed'));s.config.verificationChecks.self[0].argv=['/definitely-not-a-project-os-executable'];const r=await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['check']);expect(r.checks[0].assertions[0].status).toBe('environment-blocked');expect(r.checks[0].exitCode).toBeNull();expect(validateReceipt(r,s.read('self'),s.project('self'),s.config)).toEqual(r);});
it('cancellation retains explicit unknown execution evidence instead of claiming success',async()=>{const {s,source}=await fixture();confirm(s);enroll(s,source);registerCheck(s,'setInterval(()=>{},1000)');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),50);try{const r=await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['check'],controller.signal);expect(r.checks[0].executionError).toBe('cancelled');expect(r.checks[0].assertions[0].status).toBe('unknown');}finally{clearTimeout(timer);}});
it('fully mapped critical conditions need every current proof; a failed condition prevents whole-loop verified',async()=>{
 const {s,source}=await fixture({revision:'mapped-fixture',async analyze(i){const a=model(i);a.workflow={status:'unknown',summary:'Journey has unknown source steps',coverage:'registered-scope',unknowns:['Source step order unknown'],journeys:[{id:'journey',title:'Read current goal',purpose:'Retain goal',clauseIds:['c1'],observed:{steps:[],links:[]},desired:{steps:[],links:[]}}]};a.scenarios![0].mapping='mapped';a.scenarios![0].journeyIds=['journey'];a.scenarios![0].criteria[0].mapping='mapped';a.scenarios![0].criteria[0].journeyIds=['journey'];return a;}});
 const initial=s.read('self'),proposal=initial.scenarioSets![0];s.reviewScenarios('self',{expectedGeneration:initial.generation,idempotencyKey:'mapped-confirm',proposalId:proposal.id,decision:'confirm',author:'owner',roundId:null,scenarios:proposal.scenarios,analyze:false});enroll(s,source);
 expect(s.closedLoop('self').status).toBe('incomplete');registerCheck(s,assertion('passed'));const receipt=await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['check']);validateReceipt(receipt,s.read('self'),s.project('self'),s.config);const state=s.read('self');state.verificationReceipts=[receipt];expect(projectClosedLoop(state,receipt.binding.sourceHash).status).toBe('verified');
 registerCheck(s,assertion('behavior-failed'));const failed=await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['check']);validateReceipt(failed,s.read('self'),s.project('self'),s.config);state.verificationReceipts.push(failed);expect(projectClosedLoop(state,receipt.binding.sourceHash).status).toBe('incomplete');
});

import { projectRounds } from '../../src/core/human-goal-workflow/rounds.js';
import { probeState } from '../../scripts/project-os-verify.js';
async function retestFixture(){
 const f=await fixture();confirm(f.s);enroll(f.s,f.source);
 const outcome=join(f.root,'evidence','outcome.txt');writeFileSync(outcome,'passed');
 registerCheck(f.s,`const status=require('fs').readFileSync(${JSON.stringify(outcome)},'utf8');console.log('PROJECT_OS_ASSERTION '+JSON.stringify({assertionId:'retained',status,actual:'Actual retest fixture',evidence:'External condition changed; same source and argv'}));`,[{kind:'path',value:outcome}]);
 const execute=()=>runVerification(f.s.config,f.s.project('self'),f.s.verificationContext('self','round'),['check']);
 return {...f,outcome,execute};
}
function importReceipt(s:HumanGoalService,root:string,r:Awaited<ReturnType<typeof runVerification>>,analyze=false,key=r.id){const bytes=JSON.stringify(r),path=`${r.id}.json`;writeFileSync(join(root,'evidence',path),bytes);return s.importVerification('self',{expectedGeneration:s.read('self').generation,idempotencyKey:key,record:{rootIndex:0,path,sha256:digest(bytes)},analyze});}
it.each(['environment-blocked','behavior-failed'])('same-check explicit retest recovers %s without changing source, goal or confirmation',async status=>{
 const {s,root,outcome,execute}=await retestFixture();if(status==='environment-blocked')rmSync(outcome);else writeFileSync(outcome,status);
 const failed=await execute();importReceipt(s,root,failed);expect(s.closedLoop('self').criteria[0].status).toBe(status);
 writeFileSync(outcome,'passed');const passed=await execute();expect(passed.checks[0].configHash).toBe(failed.checks[0].configHash);expect(passed.binding).toEqual(failed.binding);importReceipt(s,root,passed);
 const c=s.closedLoop('self').criteria[0];expect(c.status).toBe('passed');expect(c.recovered).toBe(true);expect(c.evidence).toHaveLength(2);expect(c.evidence[0].current).toBe(false);expect(c.evidence[0].status).toBe(status);
});
it('new failure wins even when older success is imported last; independent success cannot erase it',async()=>{
 const {s,root,outcome,execute}=await retestFixture(),oldPass=await execute();writeFileSync(outcome,'behavior-failed');const fail=await execute();importReceipt(s,root,fail);importReceipt(s,root,oldPass);
 expect(s.closedLoop('self').criteria[0].status).toBe('behavior-failed');
 const independent={...s.config.verificationChecks.self[0],id:'independent'};s.config.verificationChecks.self.push(independent);writeFileSync(outcome,'passed');const other=await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['independent']);importReceipt(s,root,other);
 expect(s.closedLoop('self').criteria[0]).toMatchObject({status:'behavior-failed',mixed:true});
});
it.each(['unknown','cancelled'])('later same-check %s invalidates a previous pass while keeping it in history',async status=>{
 const {s,root,outcome,execute}=await retestFixture();importReceipt(s,root,await execute());writeFileSync(outcome,'unknown');
 const r=status==='cancelled'?await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['check'],AbortSignal.abort()):await execute();importReceipt(s,root,r);
 expect(s.closedLoop('self').criteria[0].status).toBe('unknown');expect(s.closedLoop('self').criteria[0].evidence.find(e=>e.status==='passed')!.current).toBe(false);
});
it('completed Agent needs proof; receipt updates round progress and survives duplicate delivery/reopen; stale and pending evidence excluded',async()=>{
 const {s,root,source,execute}=await retestFixture();writeFileSync(join(root,'evidence','stream.jsonl'),'{"type":"turn.started"}\n{"type":"turn.completed"}\n');s.follower.follow('self','registration');
 let p=projectRounds(s.read('self'));expect(p.rounds[0].status).toBe('completed');expect(p.policy.noProof).toBe(1);expect(p.rounds[0].evidenceCount).toBe(0);
 const receipt=await execute();importReceipt(s,root,receipt);importReceipt(s,root,receipt,false,'duplicate-delivery');
 p=projectRounds(s.read('self'));expect(p.rounds[0].conditionVerified).toHaveLength(1);expect(p.rounds[0].conditionVerified[0].result).toBe('passed');expect(p.rounds[0].evidenceCount).toBe(1);expect(p.rounds[0].verified).toEqual([]);expect(p.rounds[0].remaining).toContain('1/1');expect(p.policy.noProof).toBe(1); // mapping still unknown
 const config=s.config;await s.close();services.splice(services.indexOf(s),1);const reopened=new HumanGoalService(config,{revision:'fixture',async analyze(i){return model(i);}});services.push(reopened);expect(projectRounds(reopened.read('self')).rounds[0].evidenceCount).toBe(1);
 writeFileSync(join(source,'main.ts'),'export const changed=1;');p=projectRounds(reopened.read('self'),undefined,discoverSource(reopened.project('self')).hash);expect(p.rounds[0].sourceStale).toBe(true);expect(p.rounds[0].conditionVerified).toEqual([]);expect(p.rounds[0].evidenceCount).toBe(0);expect(p.rounds[0].remaining).toContain('来源已变化');
 const pending=reopened.read('self');pending.rounds!.events.push({event:{...pending.rounds!.events[0].event,key:'out-of-order',sequence:50},payloadHash:hash('out-of-order'),receivedAt:new Date().toISOString()});expect(projectRounds(pending).rounds[0].remaining).toContain('缺号');expect(projectRounds(pending).rounds[0].conditionVerified).toEqual([]);
 reopened.feedback('self',{expectedGeneration:reopened.read('self').generation,idempotencyKey:'goal-stale',originalText:'New intent',kind:'desired-change',author:'owner',provenance:'fixture',analyze:false});expect(projectRounds(reopened.read('self')).rounds[0].conditionVerified).toEqual([]);
});
it('new imports automatically reanalyze with evidence once, and reanalysis preserves confirmed human text',async()=>{
 const {s,root,execute}=await retestFixture(),before=s.read('self').attempts.length,r=await execute();
 const result:any=importReceipt(s,root,r,true);expect(result.job.attemptId).toBeTruthy();await s.idle();expect(s.read('self').attempts).toHaveLength(before+1);expect((s.read('self').attempts.at(-1)!.input.closedLoop as ReturnType<typeof projectClosedLoop>).criteria[0].status).toBe('passed');expect(s.read('self').attempts.at(-1)!.promoted).toBe(true);
 importReceipt(s,root,r,true,'same-receipt-new-request');await s.idle();expect(s.read('self').attempts).toHaveLength(before+1);expect(activeConfirmation(s.read('self'))!.scenarios[0].title).toBe('Edited by owner');
 const current=s.read('self'),confirmed=activeConfirmation(current)!;s.reviewScenarios('self',{expectedGeneration:current.generation,idempotencyKey:'revise-human',proposalId:confirmed.id,decision:'confirm',author:'owner',roundId:null,scenarios:[{...confirmed.scenarios[0],title:'Second human edit'}],analyze:false});expect(activeConfirmation(s.read('self'))!.scenarios[0].title).toBe('Second human edit');expect(s.closedLoop('self').criteria[0].status).toBe('unknown');
});
it.each(['goal','source','confirmation','evidence'])('pending evidence analysis cannot promote after %s changes',async change=>{
 let release!:()=>void,started!:()=>void;const ready=new Promise<void>(r=>started=r);let calls=0;
 const {s,root,source}=await fixture({revision:'delayed',async analyze(i){if(calls++===0)return model(i);return new Promise(r=>{release=()=>r(model(i));started();});}});confirm(s);enroll(s,source);registerCheck(s,assertion('passed'));const r=await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['check']);importReceipt(s,root,r,true);await ready;
 if(change==='goal')s.feedback('self',{expectedGeneration:s.read('self').generation,idempotencyKey:'changed-goal',originalText:'Changed goal',kind:'desired-change',author:'owner',provenance:'fixture',analyze:false});
 if(change==='source')writeFileSync(join(source,'main.ts'),'export const changed=2;');
 if(change==='confirmation'){const state=s.read('self');s.reviewScenarios('self',{expectedGeneration:state.generation,idempotencyKey:'changed-confirmation',proposalId:activeConfirmation(state)!.id,decision:'confirm',author:'owner',roundId:null,scenarios:[{...scenario,title:'Changed confirmation'}],analyze:false});}
 if(change==='evidence'){const second=await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['check']);importReceipt(s,root,second);}
 release();await s.idle();expect(s.read('self').attempts.at(-1)!.promoted).toBe(false);expect(s.read('self').attempts.at(-1)!.error).toContain('STALE_RESULT');
});
it.each(['network','invalid-json','http-error','mismatch','source-json'])('state probe distinguishes %s from environment failure and keeps raw cause',async kind=>{
 const emitted:any[]=[];let n=0;const fetcher=async()=>{n++;if(kind==='network')throw new Error('ECONNREFUSED');if(kind==='http-error')return new Response('service exception',{status:500});if(kind==='invalid-json'||kind==='source-json'&&n===2)return new Response('broken JSON');if(kind==='mismatch')return new Response(JSON.stringify({goals:[]}));return new Response(JSON.stringify({goals:[{hash:'goal',version:1}],closedLoop:{confirmation:{status:'confirmed',goalHash:'goal',goalVersion:1}},currentView:0,views:[{analysis:{purposeRefs:[{path:'main.ts',sha256:'source',start:1,end:1}]}}]}));};
 await probeState('http://127.0.0.1:9999','self',fetcher as typeof fetch,(...row)=>emitted.push(row));
 if(kind==='network'){expect(emitted[0][1]).toBe('environment-blocked');expect(emitted[1][1]).toBe('unknown');}
 else {expect(emitted.some(e=>e[1]==='behavior-failed')).toBe(true);expect(emitted.some(e=>e[1]==='environment-blocked')).toBe(false);if(kind.includes('json'))expect(emitted.some(e=>e[3].includes('broken JSON'))).toBe(true);}
 if(kind==='source-json'){expect(emitted[0][1]).toBe('passed');expect(emitted.filter(e=>e[0]==='confirmed-goal')).toHaveLength(1);}
});
it('mapped condition proof contributes to noProof policy but cannot finish other conditions',async()=>{
 const {s,source,root}=await fixture({revision:'mapped',async analyze(i){const a=model(i);a.workflow={status:'unknown',summary:'fixture',coverage:'registered-scope',unknowns:['Steps unknown'],journeys:[{id:'journey',title:'Read',purpose:'Read',clauseIds:['c1'],observed:{steps:[],links:[]},desired:{steps:[],links:[]}}]};a.scenarios![0].journeyIds=['journey'];a.scenarios![0].mapping='mapped';a.scenarios![0].criteria[0]={...a.scenarios![0].criteria[0],journeyIds:['journey'],mapping:'mapped'};a.scenarios![0].criteria.push({...a.scenarios![0].criteria[0],id:'second',text:'Second condition'});return a;}});
 const state=s.read('self'),proposal=state.scenarioSets![0];s.reviewScenarios('self',{expectedGeneration:state.generation,idempotencyKey:'mapped-confirm',proposalId:proposal.id,decision:'confirm',author:'owner',roundId:null,scenarios:proposal.scenarios,analyze:false});enroll(s,source);writeFileSync(join(root,'evidence','stream.jsonl'),'{"type":"turn.started"}\n{"type":"turn.completed"}\n');s.follower.follow('self','registration');registerCheck(s,assertion('passed'));importReceipt(s,root,await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['check']));
 const p=projectRounds(s.read('self'));expect(p.policy.noProof).toBe(0);expect(p.rounds[0].conditionProgress.status).toBe('incomplete');expect(p.rounds[0].remaining).toContain('1/2');expect(p.rounds[0].next).toContain('Second condition');
});
it('observed trace from a failed check retains failure context and cannot pass an edge',async()=>{
 const {s,source,root}=await fixture();confirm(s);enroll(s,source);const state=s.read('self'),view=state.views[state.currentView!];view.analysis.edges.push({id:'call',from:'reader',to:'reader',label:'candidate',expected:'call',actual:'source only',kind:'call',certainty:'source-supported',refs:view.analysis.modules[0].refs});s.store.save(state);
 registerCheck(s,assertion('behavior-failed')+"console.log('PROJECT_OS_TRACE '+JSON.stringify({id:'trace',from:'reader',to:'reader',edgeId:'call',traceId:'failed-call',event:'enter',evidence:'Actual entry before failure'}));process.exitCode=1;");importReceipt(s,root,await runVerification(s.config,s.project('self'),s.verificationContext('self','round'),['check']));
 expect(s.closedLoop('self').runtimeCalls[0]).toMatchObject({checkId:'check',exitCode:1,assertionStatuses:['behavior-failed'],edgePassed:false});
});
